#pragma once

// Shared file-internal helpers for the project health panel, extracted from
// ProjectHealthPanel.cpp so per-tab translation units can be split off.
// Inline so each TU compiles independently.

#include "Assets/AssetRegistry.h"
#include "Editor/EditorWidgets.h"
#include "Wheatear/Core/AssetAliasRegistry.h"
#include "Wheatear/Core/AssetPath.h"
#include "Wheatear/Core/EngineInfo.h"

#include <imgui/imgui.h>

#include <array>
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <filesystem>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace Wheatear::ProjectHealthPanelInternal {


        inline static std::string FormatBytes(uintmax_t bytes)
        {
            const char* units[] = { "B", "KB", "MB", "GB" };
            double value = static_cast<double>(bytes);
            int unit = 0;
            while (value >= 1024.0 && unit < 3)
            {
                value /= 1024.0;
                ++unit;
            }

            std::ostringstream out;
            out << std::fixed << std::setprecision(unit == 0 ? 0 : 2) << value << " " << units[unit];
            return out.str();
        }

        inline static void SummaryLine(const char* label, const std::string& value)
        {
            ImGui::TextDisabled("%s", label);
            ImGui::SameLine(180.0f);
            ImGui::TextUnformatted(value.c_str());
        }

        inline static void SummaryLine(const char* label, size_t value)
        {
            SummaryLine(label, std::to_string(value));
        }

        constexpr const char* AliasManifestHeader =
            "# Generated by Wheatear Asset Alias Manifest Editor.\n"
            "# Runtime systems read this file through AssetAliasRegistry.\n\n";

        inline static std::string ToLower(std::string value)
        {
            std::transform(value.begin(), value.end(), value.begin(),
                [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
            return value;
        }

        inline static bool IsTextHygieneAsset(const std::filesystem::path& relativePath)
        {
            const std::string extension = ToLower(relativePath.extension().generic_string());
            return extension == ".yaml"
                || extension == ".yml"
                || extension == ".json"
                || extension == ".wt"
                || extension == ".wts"
                || extension == ".vn"
                || extension == ".txt"
                || extension == ".md"
                || extension == ".csv"
                || extension == ".xml"
                || extension == ".ini"
                || extension == ".cfg"
                || extension == ".lua"
                || extension == ".cs"
                || extension == ".ps1"
                || extension == ".py"
                || extension == ".glsl"
                || extension == ".vert"
                || extension == ".frag"
                || extension == ".geom"
                || extension == ".comp"
                || extension == ".hlsl";
        }

        inline static bool IsBinaryHygieneAsset(const std::filesystem::path& relativePath)
        {
            return AssetDependencyScanner::IsPackableAsset(relativePath)
                && !IsTextHygieneAsset(relativePath);
        }

        inline static bool ReadTextFile(const std::filesystem::path& path, std::string* text)
        {
            if (!text)
                return false;

            std::ifstream input(path, std::ios::binary);
            if (!input.is_open())
                return false;

            *text = std::string(std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>());
            return true;
        }

        inline static uint64_t Hash64(const std::filesystem::path& path, bool* ok = nullptr)
        {
            constexpr uint64_t kOffset = 1469598103934665603ull;
            constexpr uint64_t kPrime = 1099511628211ull;

            std::ifstream input(path, std::ios::binary);
            if (!input.is_open())
            {
                if (ok)
                    *ok = false;
                return 0;
            }

            uint64_t hash = kOffset;
            char buffer[64 * 1024];
            while (input)
            {
                input.read(buffer, sizeof(buffer));
                const std::streamsize count = input.gcount();
                for (std::streamsize i = 0; i < count; ++i)
                {
                    hash ^= static_cast<unsigned char>(buffer[i]);
                    hash *= kPrime;
                }
            }

            if (ok)
                *ok = true;
            return hash;
        }

        inline static std::string HashToString(uint64_t value)
        {
            std::ostringstream out;
            out << std::hex << std::setw(16) << std::setfill('0') << value;
            return out.str();
        }

        inline static const char* HygieneActionTypeName(AssetHygieneActionType type)
        {
            switch (type)
            {
            case AssetHygieneActionType::ArchiveUnusedAsset: return "Archive Unused";
            case AssetHygieneActionType::ArchiveDuplicateAsset: return "Archive Duplicate";
            case AssetHygieneActionType::ReviewDuplicateAsset: return "Review Duplicate";
            case AssetHygieneActionType::ReplacePathWithAlias: return "Use Alias";
            }
            return "Action";
        }

        inline static bool ReplaceAll(std::string& text, const std::string& from, const std::string& to)
        {
            if (from.empty() || from == to)
                return false;

            bool changed = false;
            size_t offset = 0;
            while ((offset = text.find(from, offset)) != std::string::npos)
            {
                text.replace(offset, from.size(), to);
                offset += to.size();
                changed = true;
            }
            return changed;
        }

        inline static std::string NormalizedPathKey(const std::filesystem::path& path)
        {
            return AssetDependencyScanner::NormalizeAssetReference(path.generic_string());
        }

        inline static std::unordered_set<std::string> BuildPathSet(const std::vector<std::filesystem::path>& paths)
        {
            std::unordered_set<std::string> result;
            result.reserve(paths.size());
            for (const std::filesystem::path& path : paths)
                result.insert(NormalizedPathKey(path));
            return result;
        }

        inline static std::unordered_map<std::string, std::string> BuildAliasByTarget()
        {
            std::unordered_map<std::string, std::string> result;
            for (const auto& [alias, target] : AssetAliasRegistry::All())
            {
                const std::string normalized = AssetDependencyScanner::NormalizeAssetReference(target);
                if (!normalized.empty())
                {
                    auto [it, inserted] = result.emplace(normalized, alias);
                    if (!inserted && alias.size() < it->second.size())
                        it->second = alias;
                }
            }
            return result;
        }

        inline static bool IsArchivedAssetPath(const std::filesystem::path& asset)
        {
            const std::string normalized = NormalizedPathKey(asset);
            return normalized.rfind("assets/.wheatear/archive/", 0) == 0;
        }

        inline static std::filesystem::path ArchiveDestinationFor(const std::filesystem::path& projectRoot,
            const std::filesystem::path& asset)
        {
            std::filesystem::path suffix = asset;
            auto it = asset.begin();
            if (it != asset.end() && *it == "assets")
            {
                ++it;
                suffix = std::filesystem::path();
                for (; it != asset.end(); ++it)
                    suffix /= *it;
            }

            std::filesystem::path destination = projectRoot / "assets/.wheatear/archive" / suffix;
            if (!std::filesystem::exists(destination))
                return destination;

            const std::filesystem::path parent = destination.parent_path();
            const std::string stem = destination.stem().string();
            const std::string extension = destination.extension().string();
            for (int i = 2; i < 10000; ++i)
            {
                std::filesystem::path candidate = parent / (stem + "_" + std::to_string(i) + extension);
                if (!std::filesystem::exists(candidate))
                    return candidate;
            }
            return destination;
        }

        inline static bool PathInside(const std::filesystem::path& child, const std::filesystem::path& parent)
        {
            std::string childText = std::filesystem::absolute(child).lexically_normal().generic_string();
            std::string parentText = std::filesystem::absolute(parent).lexically_normal().generic_string();
            std::transform(childText.begin(), childText.end(), childText.begin(), [](unsigned char c)
            {
                return static_cast<char>(std::tolower(c));
            });
            std::transform(parentText.begin(), parentText.end(), parentText.begin(), [](unsigned char c)
            {
                return static_cast<char>(std::tolower(c));
            });

            if (childText == parentText)
                return true;
            if (!parentText.empty() && parentText.back() != '/')
                parentText.push_back('/');
            return childText.rfind(parentText, 0) == 0;
        }

        inline static bool MoveAssetToArchive(const std::filesystem::path& projectRoot,
            AssetHygieneAction& action,
            std::string* error)
        {
            const std::filesystem::path source = projectRoot / action.SourceAsset;
            std::filesystem::path destination = action.DestinationAsset;
            if (destination.is_relative())
                destination = projectRoot / destination;

            const std::filesystem::path assetsRoot = projectRoot / "assets";
            const std::filesystem::path archiveRoot = projectRoot / "assets/.wheatear/archive";
            if (!PathInside(source, assetsRoot) || !PathInside(destination, archiveRoot))
            {
                if (error)
                    *error = "Archive action blocked because the path is outside the project assets/archive roots.";
                return false;
            }

            if (!std::filesystem::is_regular_file(source))
            {
                if (error)
                    *error = "Archive source is missing: " + source.generic_string();
                return false;
            }

            if (std::filesystem::exists(destination))
                destination = ArchiveDestinationFor(projectRoot, action.SourceAsset);

            std::error_code errorCode;
            std::filesystem::create_directories(destination.parent_path(), errorCode);
            if (errorCode)
            {
                if (error)
                    *error = "Failed to create archive folder: " + errorCode.message();
                return false;
            }

            std::filesystem::rename(source, destination, errorCode);
            if (errorCode)
            {
                if (error)
                    *error = "Failed to move asset: " + errorCode.message();
                return false;
            }

            action.DestinationAsset = std::filesystem::relative(destination, projectRoot, errorCode);
            if (errorCode)
                action.DestinationAsset = destination;
            return true;
        }

        inline static bool ReplaceTextInProjectFile(const std::filesystem::path& projectRoot,
            const AssetHygieneAction& action,
            std::string* error)
        {
            const std::filesystem::path file = projectRoot.parent_path() / action.SourceFile;
            const std::filesystem::path workspaceRoot = projectRoot.parent_path();
            if (!PathInside(file, workspaceRoot) || !std::filesystem::is_regular_file(file))
            {
                if (error)
                    *error = "Replacement source file is missing or outside the workspace: " + file.generic_string();
                return false;
            }

            std::string text;
            if (!ReadTextFile(file, &text))
            {
                if (error)
                    *error = "Failed to read " + file.generic_string();
                return false;
            }

            if (!ReplaceAll(text, action.SearchText, action.ReplacementText))
            {
                if (error)
                    *error = "No matching text found in " + file.generic_string();
                return false;
            }

            if (!EditorWidgets::WriteFileText(file, text))
            {
                if (error)
                    *error = "Failed to write " + file.generic_string();
                return false;
            }
            return true;
        }

        inline static void AppendHardcodedAssetReferences(const std::filesystem::path& sourceFile,
            const std::string& text,
            std::vector<HardcodedAssetPathRecord>* records)
        {
            if (!records)
                return;

            std::vector<std::string> references;
            AssetDependencyScanner::ExtractAssetReferences(text, &references);
            std::sort(references.begin(), references.end());
            references.erase(std::unique(references.begin(), references.end()), references.end());

            for (const std::string& reference : references)
                records->push_back({ sourceFile, reference });
        }

        inline static bool IsScanTargetFile(const std::filesystem::path& path)
        {
            const std::string extension = ToLower(path.extension().generic_string());
            return extension == ".cpp"
                || extension == ".c"
                || extension == ".cc"
                || extension == ".h"
                || extension == ".hpp"
                || extension == ".inl"
                || extension == ".cs"
                || extension == ".lua"
                || extension == ".py"
                || extension == ".ps1"
                || extension == ".json"
                || extension == ".yaml"
                || extension == ".yml"
                || extension == ".md";
        }

        inline static void ScanHardcodedAssetReferences(const std::filesystem::path& root,
            std::vector<HardcodedAssetPathRecord>* records)
        {
            if (!records)
                return;

            const std::vector<std::filesystem::path> scanRoots = {
                root.parent_path() / "Wheatear" / "src",
                root.parent_path() / "WheatearEditor" / "src",
                root.parent_path() / "WheatearSandbox" / "src",
                root.parent_path() / "tools"
            };

            for (const std::filesystem::path& scanRoot : scanRoots)
            {
                if (!std::filesystem::exists(scanRoot))
                    continue;

                std::error_code error;
                for (const auto& entry : std::filesystem::recursive_directory_iterator(scanRoot, error))
                {
                    if (error || !entry.is_regular_file())
                        continue;

                    const std::filesystem::path relativePath = entry.path();
                    if (!IsScanTargetFile(relativePath))
                        continue;

                    std::string text;
                    if (!ReadTextFile(entry.path(), &text))
                        continue;

                    std::error_code relativeError;
                    std::filesystem::path sourceFile = std::filesystem::relative(entry.path(), root.parent_path(), relativeError);
                    if (relativeError)
                        sourceFile = entry.path();
                    AppendHardcodedAssetReferences(sourceFile, text, records);
                }
            }
        }

        struct AliasManifestRow
        {
            std::string Alias;
            std::string Target;
        };

        inline static std::vector<std::string> SplitAliasPath(const std::string& alias)
        {
            std::vector<std::string> parts;
            std::stringstream stream(alias);
            std::string part;
            while (std::getline(stream, part, '.'))
            {
                if (!part.empty())
                    parts.push_back(part);
            }
            return parts;
        }

        inline static std::string ScalarText(const YAML::Node& node)
        {
            if (!node || !node.IsDefined() || node.IsNull())
                return {};

            try
            {
                return node.as<std::string>("");
            }
            catch (...)
            {
                return {};
            }
        }

        inline static void FlattenAliases(const YAML::Node& node,
            const std::string& prefix,
            std::vector<AliasManifestRow>* rows)
        {
            if (!node || !rows)
                return;

            if (node.IsMap())
            {
                for (const auto& entry : node)
                {
                    if (!entry.first.IsScalar())
                        continue;

                    const std::string key = entry.first.as<std::string>("");
                    if (key.empty())
                        continue;

                    const std::string nextPrefix = prefix.empty() ? key : prefix + "." + key;
                    FlattenAliases(entry.second, nextPrefix, rows);
                }
                return;
            }

            if (!prefix.empty() && node.IsScalar())
                rows->push_back({ prefix, ScalarText(node) });
        }

        inline static std::vector<AliasManifestRow> BuildAliasRows(YAML::Node root)
        {
            std::vector<AliasManifestRow> rows;
            YAML::Node aliases = root["aliases"] ? root["aliases"] : root;
            FlattenAliases(aliases, {}, &rows);
            std::sort(rows.begin(), rows.end(), [](const AliasManifestRow& left, const AliasManifestRow& right)
            {
                return left.Alias < right.Alias;
            });
            return rows;
        }

        inline static YAML::Node AliasRoot(YAML::Node root)
        {
            YAML::Node aliases = root["aliases"];
            if (!aliases || !aliases.IsMap())
            {
                root["aliases"] = YAML::Node(YAML::NodeType::Map);
                aliases = root["aliases"];
            }
            return aliases;
        }

        inline static bool SetAliasTarget(YAML::Node root, const std::string& alias, const std::string& target)
        {
            const std::vector<std::string> parts = SplitAliasPath(alias);
            if (parts.empty())
                return false;

            YAML::Node cursor = AliasRoot(root);
            for (size_t i = 0; i + 1 < parts.size(); ++i)
            {
                YAML::Node child = cursor[parts[i]];
                if (!child || !child.IsMap())
                    cursor[parts[i]] = YAML::Node(YAML::NodeType::Map);
                cursor = cursor[parts[i]];
            }

            cursor[parts.back()] = target;
            return true;
        }

        inline static bool RemoveAliasTarget(YAML::Node root, const std::string& alias)
        {
            const std::vector<std::string> parts = SplitAliasPath(alias);
            if (parts.empty())
                return false;

            YAML::Node cursor = AliasRoot(root);
            for (size_t i = 0; i + 1 < parts.size(); ++i)
            {
                cursor = cursor[parts[i]];
                if (!cursor || !cursor.IsMap())
                    return false;
            }

            return cursor.remove(parts.back());
        }

        inline static AssetHygieneReport BuildAssetHygieneReport(const std::filesystem::path& projectRoot,
            const AssetDependencyReport& dependencyReport)
        {
            AssetHygieneReport report;
            const auto& registry = AssetRegistry::Get();
            const auto& assets = registry.GetAssets();

            std::unordered_set<std::string> packedAssets;
            packedAssets.reserve(dependencyReport.IncludedAssets.size());
            for (const auto& asset : dependencyReport.IncludedAssets)
                packedAssets.insert(AssetDependencyScanner::NormalizeAssetReference(asset.generic_string()));

            std::unordered_set<std::string> unusedAssets;
            unusedAssets.reserve(dependencyReport.UnusedAssets.size());
            for (const auto& asset : dependencyReport.UnusedAssets)
                unusedAssets.insert(AssetDependencyScanner::NormalizeAssetReference(asset.generic_string()));

            std::unordered_map<uintmax_t, std::vector<const EditorAssetMetadata*>> candidatesBySize;
            candidatesBySize.reserve(assets.size());

            for (const EditorAssetMetadata& metadata : assets)
            {
                const std::filesystem::path relativePath(metadata.RelativePath);
                if (!IsBinaryHygieneAsset(relativePath))
                    continue;

                const bool packed = packedAssets.count(AssetDependencyScanner::NormalizeAssetReference(metadata.RelativePath)) != 0;
                const bool unused = unusedAssets.count(AssetDependencyScanner::NormalizeAssetReference(metadata.RelativePath)) != 0;
                report.LargestAssets.push_back({ relativePath, metadata.SizeBytes, packed, unused });
                if (metadata.SizeBytes > 0)
                    candidatesBySize[metadata.SizeBytes].push_back(&metadata);
            }

            std::sort(report.LargestAssets.begin(), report.LargestAssets.end(),
                [](const AssetSizeRecord& left, const AssetSizeRecord& right)
                {
                    if (left.SizeBytes != right.SizeBytes)
                        return left.SizeBytes > right.SizeBytes;
                    return left.Asset.generic_string() < right.Asset.generic_string();
                });
            if (report.LargestAssets.size() > 200)
                report.LargestAssets.resize(200);

            for (const auto& [sizeBytes, candidates] : candidatesBySize)
            {
                if (candidates.size() < 2)
                    continue;

                std::unordered_map<uint64_t, AssetDuplicateGroup> groupsByHash;
                for (const EditorAssetMetadata* metadata : candidates)
                {
                    const std::filesystem::path absolutePath = projectRoot / metadata->RelativePath;
                    bool ok = false;
                    const uint64_t hash = Hash64(absolutePath, &ok);
                    if (!ok)
                        continue;

                    auto& group = groupsByHash[hash];
                    group.Hash = HashToString(hash);
                    group.SizeBytes = sizeBytes;
                    group.Assets.emplace_back(metadata->RelativePath);
                }

                for (auto& [hash, group] : groupsByHash)
                {
                    if (group.Assets.size() < 2)
                        continue;

                    report.DuplicateExtraAssetCount += group.Assets.size() - 1;
                    report.DuplicateExtraBytes += (group.Assets.size() - 1) * group.SizeBytes;
                    std::sort(group.Assets.begin(), group.Assets.end());
                    report.DuplicateGroups.push_back(std::move(group));
                }
            }

            std::sort(report.DuplicateGroups.begin(), report.DuplicateGroups.end(),
                [](const AssetDuplicateGroup& left, const AssetDuplicateGroup& right)
                {
                    if (left.SizeBytes != right.SizeBytes)
                        return left.SizeBytes > right.SizeBytes;
                    return left.Hash < right.Hash;
                });

            for (const auto& [alias, target] : AssetAliasRegistry::All())
            {
                const std::string normalizedTarget = AssetDependencyScanner::NormalizeAssetReference(target);
                if (normalizedTarget.empty())
                {
                    report.AliasIssues.push_back({ alias, target, "Empty alias target." });
                    continue;
                }

                const std::filesystem::path targetPath = projectRoot / normalizedTarget;
                if (!std::filesystem::exists(targetPath))
                {
                    report.AliasIssues.push_back({ alias, normalizedTarget, "Target file is missing." });
                    continue;
                }

                if (std::filesystem::is_directory(targetPath))
                    continue;

                if (AssetDependencyScanner::IsPackableAsset(std::filesystem::path(normalizedTarget)) && !packedAssets.count(normalizedTarget))
                    report.AliasIssues.push_back({ alias, normalizedTarget, "Target is not in the current package closure." });
            }

            std::sort(report.AliasIssues.begin(), report.AliasIssues.end(),
                [](const AssetAliasIssue& left, const AssetAliasIssue& right)
                {
                    return std::tie(left.Alias, left.Target, left.Issue)
                        < std::tie(right.Alias, right.Target, right.Issue);
                });

            ScanHardcodedAssetReferences(projectRoot, &report.HardcodedAssetPaths);
            std::sort(report.HardcodedAssetPaths.begin(), report.HardcodedAssetPaths.end(),
                [](const HardcodedAssetPathRecord& left, const HardcodedAssetPathRecord& right)
                {
                    return std::tie(left.SourceFile, left.Reference)
                        < std::tie(right.SourceFile, right.Reference);
                });
            report.HardcodedAssetPaths.erase(
                std::unique(report.HardcodedAssetPaths.begin(), report.HardcodedAssetPaths.end(),
                    [](const HardcodedAssetPathRecord& left, const HardcodedAssetPathRecord& right)
                    {
                        return left.SourceFile == right.SourceFile && left.Reference == right.Reference;
                    }),
                report.HardcodedAssetPaths.end());

            return report;
        }



} // namespace Wheatear::ProjectHealthPanelInternal
