#include "wepch.h"
#include "ProjectHealthPanel.h"

#include "Assets/AssetRegistry.h"
#include "Editor/EditorFloatingWindow.h"
#include "Editor/EditorLocale.h"
#include "Editor/EditorWidgets.h"
#include "Editor/GameplayEditorShell.h"
#include "Wheatear/Core/AssetAliasRegistry.h"
#include "Wheatear/Core/AssetPath.h"
#include "Wheatear/Core/EngineInfo.h"

#include <imgui/imgui.h>

#include <array>
#include <algorithm>
#include <cctype>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <tuple>
#include <iterator>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace Wheatear {

    namespace {

        static std::string FormatBytes(uintmax_t bytes)
        {
            const char* units[] = { "B", "KB", "MB", "GB" };
            double value = static_cast<double>(bytes);
            int unit = 0;
            while (value >= 1024.0 && unit < 3)
            {
                value /= 1024.0;
                ++unit;
            }

            std::ostringstream out;
            out << std::fixed << std::setprecision(unit == 0 ? 0 : 2) << value << " " << units[unit];
            return out.str();
        }

        static void SummaryLine(const char* label, const std::string& value)
        {
            ImGui::TextDisabled("%s", label);
            ImGui::SameLine(180.0f);
            ImGui::TextUnformatted(value.c_str());
        }

        static void SummaryLine(const char* label, size_t value)
        {
            SummaryLine(label, std::to_string(value));
        }

        constexpr const char* AliasManifestHeader =
            "# Generated by Wheatear Asset Alias Manifest Editor.\n"
            "# Runtime systems read this file through AssetAliasRegistry.\n\n";

        static std::string ToLower(std::string value)
        {
            std::transform(value.begin(), value.end(), value.begin(),
                [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
            return value;
        }

        static bool IsTextHygieneAsset(const std::filesystem::path& relativePath)
        {
            const std::string extension = ToLower(relativePath.extension().generic_string());
            return extension == ".yaml"
                || extension == ".yml"
                || extension == ".json"
                || extension == ".wt"
                || extension == ".wts"
                || extension == ".vn"
                || extension == ".txt"
                || extension == ".md"
                || extension == ".csv"
                || extension == ".xml"
                || extension == ".ini"
                || extension == ".cfg"
                || extension == ".lua"
                || extension == ".cs"
                || extension == ".ps1"
                || extension == ".py"
                || extension == ".glsl"
                || extension == ".vert"
                || extension == ".frag"
                || extension == ".geom"
                || extension == ".comp"
                || extension == ".hlsl";
        }

        static bool IsBinaryHygieneAsset(const std::filesystem::path& relativePath)
        {
            return AssetDependencyScanner::IsPackableAsset(relativePath)
                && !IsTextHygieneAsset(relativePath);
        }

        static bool ReadTextFile(const std::filesystem::path& path, std::string* text)
        {
            if (!text)
                return false;

            std::ifstream input(path, std::ios::binary);
            if (!input.is_open())
                return false;

            *text = std::string(std::istreambuf_iterator<char>(input), std::istreambuf_iterator<char>());
            return true;
        }

        static uint64_t Hash64(const std::filesystem::path& path, bool* ok = nullptr)
        {
            constexpr uint64_t kOffset = 1469598103934665603ull;
            constexpr uint64_t kPrime = 1099511628211ull;

            std::ifstream input(path, std::ios::binary);
            if (!input.is_open())
            {
                if (ok)
                    *ok = false;
                return 0;
            }

            uint64_t hash = kOffset;
            char buffer[64 * 1024];
            while (input)
            {
                input.read(buffer, sizeof(buffer));
                const std::streamsize count = input.gcount();
                for (std::streamsize i = 0; i < count; ++i)
                {
                    hash ^= static_cast<unsigned char>(buffer[i]);
                    hash *= kPrime;
                }
            }

            if (ok)
                *ok = true;
            return hash;
        }

        static std::string HashToString(uint64_t value)
        {
            std::ostringstream out;
            out << std::hex << std::setw(16) << std::setfill('0') << value;
            return out.str();
        }

        static const char* HygieneActionTypeName(AssetHygieneActionType type)
        {
            switch (type)
            {
            case AssetHygieneActionType::ArchiveUnusedAsset: return "Archive Unused";
            case AssetHygieneActionType::ArchiveDuplicateAsset: return "Archive Duplicate";
            case AssetHygieneActionType::ReviewDuplicateAsset: return "Review Duplicate";
            case AssetHygieneActionType::ReplacePathWithAlias: return "Use Alias";
            }
            return "Action";
        }

        static bool ReplaceAll(std::string& text, const std::string& from, const std::string& to)
        {
            if (from.empty() || from == to)
                return false;

            bool changed = false;
            size_t offset = 0;
            while ((offset = text.find(from, offset)) != std::string::npos)
            {
                text.replace(offset, from.size(), to);
                offset += to.size();
                changed = true;
            }
            return changed;
        }

        static std::string NormalizedPathKey(const std::filesystem::path& path)
        {
            return AssetDependencyScanner::NormalizeAssetReference(path.generic_string());
        }

        static std::unordered_set<std::string> BuildPathSet(const std::vector<std::filesystem::path>& paths)
        {
            std::unordered_set<std::string> result;
            result.reserve(paths.size());
            for (const std::filesystem::path& path : paths)
                result.insert(NormalizedPathKey(path));
            return result;
        }

        static std::unordered_map<std::string, std::string> BuildAliasByTarget()
        {
            std::unordered_map<std::string, std::string> result;
            for (const auto& [alias, target] : AssetAliasRegistry::All())
            {
                const std::string normalized = AssetDependencyScanner::NormalizeAssetReference(target);
                if (!normalized.empty())
                {
                    auto [it, inserted] = result.emplace(normalized, alias);
                    if (!inserted && alias.size() < it->second.size())
                        it->second = alias;
                }
            }
            return result;
        }

        static bool IsArchivedAssetPath(const std::filesystem::path& asset)
        {
            const std::string normalized = NormalizedPathKey(asset);
            return normalized.rfind("assets/.wheatear/archive/", 0) == 0;
        }

        static std::filesystem::path ArchiveDestinationFor(const std::filesystem::path& projectRoot,
            const std::filesystem::path& asset)
        {
            std::filesystem::path suffix = asset;
            auto it = asset.begin();
            if (it != asset.end() && *it == "assets")
            {
                ++it;
                suffix = std::filesystem::path();
                for (; it != asset.end(); ++it)
                    suffix /= *it;
            }

            std::filesystem::path destination = projectRoot / "assets/.wheatear/archive" / suffix;
            if (!std::filesystem::exists(destination))
                return destination;

            const std::filesystem::path parent = destination.parent_path();
            const std::string stem = destination.stem().string();
            const std::string extension = destination.extension().string();
            for (int i = 2; i < 10000; ++i)
            {
                std::filesystem::path candidate = parent / (stem + "_" + std::to_string(i) + extension);
                if (!std::filesystem::exists(candidate))
                    return candidate;
            }
            return destination;
        }

        static bool PathInside(const std::filesystem::path& child, const std::filesystem::path& parent)
        {
            std::string childText = std::filesystem::absolute(child).lexically_normal().generic_string();
            std::string parentText = std::filesystem::absolute(parent).lexically_normal().generic_string();
            std::transform(childText.begin(), childText.end(), childText.begin(), [](unsigned char c)
            {
                return static_cast<char>(std::tolower(c));
            });
            std::transform(parentText.begin(), parentText.end(), parentText.begin(), [](unsigned char c)
            {
                return static_cast<char>(std::tolower(c));
            });

            if (childText == parentText)
                return true;
            if (!parentText.empty() && parentText.back() != '/')
                parentText.push_back('/');
            return childText.rfind(parentText, 0) == 0;
        }

        static bool MoveAssetToArchive(const std::filesystem::path& projectRoot,
            AssetHygieneAction& action,
            std::string* error)
        {
            const std::filesystem::path source = projectRoot / action.SourceAsset;
            std::filesystem::path destination = action.DestinationAsset;
            if (destination.is_relative())
                destination = projectRoot / destination;

            const std::filesystem::path assetsRoot = projectRoot / "assets";
            const std::filesystem::path archiveRoot = projectRoot / "assets/.wheatear/archive";
            if (!PathInside(source, assetsRoot) || !PathInside(destination, archiveRoot))
            {
                if (error)
                    *error = "Archive action blocked because the path is outside the project assets/archive roots.";
                return false;
            }

            if (!std::filesystem::is_regular_file(source))
            {
                if (error)
                    *error = "Archive source is missing: " + source.generic_string();
                return false;
            }

            if (std::filesystem::exists(destination))
                destination = ArchiveDestinationFor(projectRoot, action.SourceAsset);

            std::error_code errorCode;
            std::filesystem::create_directories(destination.parent_path(), errorCode);
            if (errorCode)
            {
                if (error)
                    *error = "Failed to create archive folder: " + errorCode.message();
                return false;
            }

            std::filesystem::rename(source, destination, errorCode);
            if (errorCode)
            {
                if (error)
                    *error = "Failed to move asset: " + errorCode.message();
                return false;
            }

            action.DestinationAsset = std::filesystem::relative(destination, projectRoot, errorCode);
            if (errorCode)
                action.DestinationAsset = destination;
            return true;
        }

        static bool ReplaceTextInProjectFile(const std::filesystem::path& projectRoot,
            const AssetHygieneAction& action,
            std::string* error)
        {
            const std::filesystem::path file = projectRoot.parent_path() / action.SourceFile;
            const std::filesystem::path workspaceRoot = projectRoot.parent_path();
            if (!PathInside(file, workspaceRoot) || !std::filesystem::is_regular_file(file))
            {
                if (error)
                    *error = "Replacement source file is missing or outside the workspace: " + file.generic_string();
                return false;
            }

            std::string text;
            if (!ReadTextFile(file, &text))
            {
                if (error)
                    *error = "Failed to read " + file.generic_string();
                return false;
            }

            if (!ReplaceAll(text, action.SearchText, action.ReplacementText))
            {
                if (error)
                    *error = "No matching text found in " + file.generic_string();
                return false;
            }

            if (!EditorWidgets::WriteFileText(file, text))
            {
                if (error)
                    *error = "Failed to write " + file.generic_string();
                return false;
            }
            return true;
        }

        static void AppendHardcodedAssetReferences(const std::filesystem::path& sourceFile,
            const std::string& text,
            std::vector<HardcodedAssetPathRecord>* records)
        {
            if (!records)
                return;

            std::vector<std::string> references;
            AssetDependencyScanner::ExtractAssetReferences(text, &references);
            std::sort(references.begin(), references.end());
            references.erase(std::unique(references.begin(), references.end()), references.end());

            for (const std::string& reference : references)
                records->push_back({ sourceFile, reference });
        }

        static bool IsScanTargetFile(const std::filesystem::path& path)
        {
            const std::string extension = ToLower(path.extension().generic_string());
            return extension == ".cpp"
                || extension == ".c"
                || extension == ".cc"
                || extension == ".h"
                || extension == ".hpp"
                || extension == ".inl"
                || extension == ".cs"
                || extension == ".lua"
                || extension == ".py"
                || extension == ".ps1"
                || extension == ".json"
                || extension == ".yaml"
                || extension == ".yml"
                || extension == ".md";
        }

        static void ScanHardcodedAssetReferences(const std::filesystem::path& root,
            std::vector<HardcodedAssetPathRecord>* records)
        {
            if (!records)
                return;

            const std::vector<std::filesystem::path> scanRoots = {
                root.parent_path() / "Wheatear" / "src",
                root.parent_path() / "WheatearEditor" / "src",
                root.parent_path() / "WheatearSandbox" / "src",
                root.parent_path() / "tools"
            };

            for (const std::filesystem::path& scanRoot : scanRoots)
            {
                if (!std::filesystem::exists(scanRoot))
                    continue;

                std::error_code error;
                for (const auto& entry : std::filesystem::recursive_directory_iterator(scanRoot, error))
                {
                    if (error || !entry.is_regular_file())
                        continue;

                    const std::filesystem::path relativePath = entry.path();
                    if (!IsScanTargetFile(relativePath))
                        continue;

                    std::string text;
                    if (!ReadTextFile(entry.path(), &text))
                        continue;

                    std::error_code relativeError;
                    std::filesystem::path sourceFile = std::filesystem::relative(entry.path(), root.parent_path(), relativeError);
                    if (relativeError)
                        sourceFile = entry.path();
                    AppendHardcodedAssetReferences(sourceFile, text, records);
                }
            }
        }

        struct AliasManifestRow
        {
            std::string Alias;
            std::string Target;
        };

        static std::vector<std::string> SplitAliasPath(const std::string& alias)
        {
            std::vector<std::string> parts;
            std::stringstream stream(alias);
            std::string part;
            while (std::getline(stream, part, '.'))
            {
                if (!part.empty())
                    parts.push_back(part);
            }
            return parts;
        }

        static std::string ScalarText(const YAML::Node& node)
        {
            if (!node || !node.IsDefined() || node.IsNull())
                return {};

            try
            {
                return node.as<std::string>("");
            }
            catch (...)
            {
                return {};
            }
        }

        static void FlattenAliases(const YAML::Node& node,
            const std::string& prefix,
            std::vector<AliasManifestRow>* rows)
        {
            if (!node || !rows)
                return;

            if (node.IsMap())
            {
                for (const auto& entry : node)
                {
                    if (!entry.first.IsScalar())
                        continue;

                    const std::string key = entry.first.as<std::string>("");
                    if (key.empty())
                        continue;

                    const std::string nextPrefix = prefix.empty() ? key : prefix + "." + key;
                    FlattenAliases(entry.second, nextPrefix, rows);
                }
                return;
            }

            if (!prefix.empty() && node.IsScalar())
                rows->push_back({ prefix, ScalarText(node) });
        }

        static std::vector<AliasManifestRow> BuildAliasRows(YAML::Node root)
        {
            std::vector<AliasManifestRow> rows;
            YAML::Node aliases = root["aliases"] ? root["aliases"] : root;
            FlattenAliases(aliases, {}, &rows);
            std::sort(rows.begin(), rows.end(), [](const AliasManifestRow& left, const AliasManifestRow& right)
            {
                return left.Alias < right.Alias;
            });
            return rows;
        }

        static YAML::Node AliasRoot(YAML::Node root)
        {
            YAML::Node aliases = root["aliases"];
            if (!aliases || !aliases.IsMap())
            {
                root["aliases"] = YAML::Node(YAML::NodeType::Map);
                aliases = root["aliases"];
            }
            return aliases;
        }

        static bool SetAliasTarget(YAML::Node root, const std::string& alias, const std::string& target)
        {
            const std::vector<std::string> parts = SplitAliasPath(alias);
            if (parts.empty())
                return false;

            YAML::Node cursor = AliasRoot(root);
            for (size_t i = 0; i + 1 < parts.size(); ++i)
            {
                YAML::Node child = cursor[parts[i]];
                if (!child || !child.IsMap())
                    cursor[parts[i]] = YAML::Node(YAML::NodeType::Map);
                cursor = cursor[parts[i]];
            }

            cursor[parts.back()] = target;
            return true;
        }

        static bool RemoveAliasTarget(YAML::Node root, const std::string& alias)
        {
            const std::vector<std::string> parts = SplitAliasPath(alias);
            if (parts.empty())
                return false;

            YAML::Node cursor = AliasRoot(root);
            for (size_t i = 0; i + 1 < parts.size(); ++i)
            {
                cursor = cursor[parts[i]];
                if (!cursor || !cursor.IsMap())
                    return false;
            }

            return cursor.remove(parts.back());
        }

        static AssetHygieneReport BuildAssetHygieneReport(const std::filesystem::path& projectRoot,
            const AssetDependencyReport& dependencyReport)
        {
            AssetHygieneReport report;
            const auto& registry = AssetRegistry::Get();
            const auto& assets = registry.GetAssets();

            std::unordered_set<std::string> packedAssets;
            packedAssets.reserve(dependencyReport.IncludedAssets.size());
            for (const auto& asset : dependencyReport.IncludedAssets)
                packedAssets.insert(AssetDependencyScanner::NormalizeAssetReference(asset.generic_string()));

            std::unordered_set<std::string> unusedAssets;
            unusedAssets.reserve(dependencyReport.UnusedAssets.size());
            for (const auto& asset : dependencyReport.UnusedAssets)
                unusedAssets.insert(AssetDependencyScanner::NormalizeAssetReference(asset.generic_string()));

            std::unordered_map<uintmax_t, std::vector<const EditorAssetMetadata*>> candidatesBySize;
            candidatesBySize.reserve(assets.size());

            for (const EditorAssetMetadata& metadata : assets)
            {
                const std::filesystem::path relativePath(metadata.RelativePath);
                if (!IsBinaryHygieneAsset(relativePath))
                    continue;

                const bool packed = packedAssets.count(AssetDependencyScanner::NormalizeAssetReference(metadata.RelativePath)) != 0;
                const bool unused = unusedAssets.count(AssetDependencyScanner::NormalizeAssetReference(metadata.RelativePath)) != 0;
                report.LargestAssets.push_back({ relativePath, metadata.SizeBytes, packed, unused });
                if (metadata.SizeBytes > 0)
                    candidatesBySize[metadata.SizeBytes].push_back(&metadata);
            }

            std::sort(report.LargestAssets.begin(), report.LargestAssets.end(),
                [](const AssetSizeRecord& left, const AssetSizeRecord& right)
                {
                    if (left.SizeBytes != right.SizeBytes)
                        return left.SizeBytes > right.SizeBytes;
                    return left.Asset.generic_string() < right.Asset.generic_string();
                });
            if (report.LargestAssets.size() > 200)
                report.LargestAssets.resize(200);

            for (const auto& [sizeBytes, candidates] : candidatesBySize)
            {
                if (candidates.size() < 2)
                    continue;

                std::unordered_map<uint64_t, AssetDuplicateGroup> groupsByHash;
                for (const EditorAssetMetadata* metadata : candidates)
                {
                    const std::filesystem::path absolutePath = projectRoot / metadata->RelativePath;
                    bool ok = false;
                    const uint64_t hash = Hash64(absolutePath, &ok);
                    if (!ok)
                        continue;

                    auto& group = groupsByHash[hash];
                    group.Hash = HashToString(hash);
                    group.SizeBytes = sizeBytes;
                    group.Assets.emplace_back(metadata->RelativePath);
                }

                for (auto& [hash, group] : groupsByHash)
                {
                    if (group.Assets.size() < 2)
                        continue;

                    report.DuplicateExtraAssetCount += group.Assets.size() - 1;
                    report.DuplicateExtraBytes += (group.Assets.size() - 1) * group.SizeBytes;
                    std::sort(group.Assets.begin(), group.Assets.end());
                    report.DuplicateGroups.push_back(std::move(group));
                }
            }

            std::sort(report.DuplicateGroups.begin(), report.DuplicateGroups.end(),
                [](const AssetDuplicateGroup& left, const AssetDuplicateGroup& right)
                {
                    if (left.SizeBytes != right.SizeBytes)
                        return left.SizeBytes > right.SizeBytes;
                    return left.Hash < right.Hash;
                });

            for (const auto& [alias, target] : AssetAliasRegistry::All())
            {
                const std::string normalizedTarget = AssetDependencyScanner::NormalizeAssetReference(target);
                if (normalizedTarget.empty())
                {
                    report.AliasIssues.push_back({ alias, target, "Empty alias target." });
                    continue;
                }

                const std::filesystem::path targetPath = projectRoot / normalizedTarget;
                if (!std::filesystem::exists(targetPath))
                {
                    report.AliasIssues.push_back({ alias, normalizedTarget, "Target file is missing." });
                    continue;
                }

                if (std::filesystem::is_directory(targetPath))
                    continue;

                if (AssetDependencyScanner::IsPackableAsset(std::filesystem::path(normalizedTarget)) && !packedAssets.count(normalizedTarget))
                    report.AliasIssues.push_back({ alias, normalizedTarget, "Target is not in the current package closure." });
            }

            std::sort(report.AliasIssues.begin(), report.AliasIssues.end(),
                [](const AssetAliasIssue& left, const AssetAliasIssue& right)
                {
                    return std::tie(left.Alias, left.Target, left.Issue)
                        < std::tie(right.Alias, right.Target, right.Issue);
                });

            ScanHardcodedAssetReferences(projectRoot, &report.HardcodedAssetPaths);
            std::sort(report.HardcodedAssetPaths.begin(), report.HardcodedAssetPaths.end(),
                [](const HardcodedAssetPathRecord& left, const HardcodedAssetPathRecord& right)
                {
                    return std::tie(left.SourceFile, left.Reference)
                        < std::tie(right.SourceFile, right.Reference);
                });
            report.HardcodedAssetPaths.erase(
                std::unique(report.HardcodedAssetPaths.begin(), report.HardcodedAssetPaths.end(),
                    [](const HardcodedAssetPathRecord& left, const HardcodedAssetPathRecord& right)
                    {
                        return left.SourceFile == right.SourceFile && left.Reference == right.Reference;
                    }),
                report.HardcodedAssetPaths.end());

            return report;
        }

    } // namespace

    void ProjectHealthPanel::Open(const EditorToolContext&)
    {
        m_Open = true;
        if (m_StartupScene.empty())
            m_StartupScene = EngineInfo::DefaultStartupScene;
        if (!m_AliasManifestDocument.IsLoaded())
            LoadAliasManifest();
        Refresh();
    }

    void ProjectHealthPanel::LoadAliasManifest()
    {
        m_AliasManifestDocument.SetSourcePath(m_AliasManifestPath);
        m_AliasManifestDocument.Load();
        m_AliasStatus = m_AliasManifestDocument.GetStatus();
        m_SelectedAlias.clear();
    }

    void ProjectHealthPanel::SaveAliasManifest()
    {
        if (m_AliasManifestDocument.Save(AliasManifestHeader))
        {
            AssetAliasRegistry::Reload(m_AliasManifestPath);
            m_AliasStatus = "Alias manifest saved and registry reloaded.";
            Refresh();
        }
        else
        {
            m_AliasStatus = m_AliasManifestDocument.GetStatus();
        }
    }

    void ProjectHealthPanel::Refresh()
    {
        AssetDependencyScanOptions options;
        options.ProjectRoot = AssetPath::GetProjectRoot();
        options.StartupAsset = m_StartupScene;
        options.EnableScripts = m_EnableScripts;
        options.IncludeBuiltinAssets = true;
        options.IncludeUnusedAssets = m_IncludeUnusedAssets;

        m_Report = AssetDependencyScanner::BuildReport(options);
        m_SourceReport = ProjectSourceScanner::BuildReport(options.ProjectRoot);
        AssetRegistry::Get().Scan(options.ProjectRoot);
        AssetRegistry::Get().WriteRegistry();
        m_HygieneReport = BuildAssetHygieneReport(options.ProjectRoot, m_Report);
        const size_t sourceSyncIssues = m_SourceReport.MissingFromProject.size()
            + m_SourceReport.StaleProjectEntries.size();
        m_Status = "Last scan: " + std::to_string(m_Report.IncludedAssets.size()) + " assets, "
            + std::to_string(m_Report.MissingReferences.size()) + " missing references, "
            + std::to_string(m_Report.MissingSceneTransitions.size()) + " missing scene transition(s), "
            + std::to_string(sourceSyncIssues) + " source sync issue(s), "
            + std::to_string(m_HygieneReport.DuplicateGroups.size()) + " duplicate group(s), "
            + std::to_string(m_HygieneReport.AliasIssues.size()) + " alias issue(s).";
    }

    void ProjectHealthPanel::BuildHygieneCleanupPlan()
    {
        m_HygieneActions.clear();

        const std::filesystem::path projectRoot = AssetPath::GetProjectRoot();
        const std::unordered_set<std::string> packedAssets = BuildPathSet(m_Report.IncludedAssets);
        const std::unordered_set<std::string> unusedAssets = BuildPathSet(m_Report.UnusedAssets);
        const std::unordered_map<std::string, std::string> aliasByTarget = BuildAliasByTarget();
        std::unordered_set<std::string> plannedArchiveAssets;

        auto makeArchiveDestination = [&](const std::filesystem::path& asset)
        {
            std::error_code error;
            std::filesystem::path destination = ArchiveDestinationFor(projectRoot, asset);
            std::filesystem::path relative = std::filesystem::relative(destination, projectRoot, error);
            return error ? destination : relative;
        };

        auto assetSize = [&](const std::filesystem::path& asset)
        {
            std::error_code error;
            const uintmax_t size = std::filesystem::file_size(projectRoot / asset, error);
            return error ? static_cast<uintmax_t>(0) : size;
        };

        for (const AssetDuplicateGroup& group : m_HygieneReport.DuplicateGroups)
        {
            if (group.Assets.size() < 2)
                continue;

            std::filesystem::path keep = group.Assets.front();
            for (const std::filesystem::path& asset : group.Assets)
            {
                if (packedAssets.count(NormalizedPathKey(asset)) != 0)
                {
                    keep = asset;
                    break;
                }
            }

            for (const std::filesystem::path& asset : group.Assets)
            {
                const std::string normalized = NormalizedPathKey(asset);
                if (asset == keep || IsArchivedAssetPath(asset))
                    continue;

                const bool unused = unusedAssets.count(normalized) != 0;
                const bool aliased = aliasByTarget.find(normalized) != aliasByTarget.end();

                AssetHygieneAction action;
                action.Type = unused && !aliased
                    ? AssetHygieneActionType::ArchiveDuplicateAsset
                    : AssetHygieneActionType::ReviewDuplicateAsset;
                action.CanApply = action.Type == AssetHygieneActionType::ArchiveDuplicateAsset;
                action.Selected = action.CanApply;
                action.Title = action.CanApply ? "Archive unused duplicate asset" : "Review duplicate before changing references";
                action.Detail = "Keep " + keep.generic_string() + "; duplicate " + asset.generic_string()
                    + (aliased ? " is an alias target." : ".");
                action.SourceAsset = asset;
                action.DestinationAsset = makeArchiveDestination(asset);
                action.SizeBytes = group.SizeBytes;
                plannedArchiveAssets.insert(normalized);
                m_HygieneActions.push_back(std::move(action));
            }
        }

        for (const std::filesystem::path& asset : m_Report.UnusedAssets)
        {
            const std::string normalized = NormalizedPathKey(asset);
            if (plannedArchiveAssets.count(normalized) != 0
                || aliasByTarget.find(normalized) != aliasByTarget.end()
                || IsArchivedAssetPath(asset)
                || !IsBinaryHygieneAsset(asset))
                continue;

            AssetHygieneAction action;
            action.Type = AssetHygieneActionType::ArchiveUnusedAsset;
            action.CanApply = true;
            action.Selected = true;
            action.Title = "Archive unused binary asset";
            action.Detail = "Not included in the current package closure and not targeted by an alias.";
            action.SourceAsset = asset;
            action.DestinationAsset = makeArchiveDestination(asset);
            action.SizeBytes = assetSize(asset);
            m_HygieneActions.push_back(std::move(action));
        }

        std::unordered_set<std::string> replacementKeys;
        for (const HardcodedAssetPathRecord& record : m_HygieneReport.HardcodedAssetPaths)
        {
            const std::string normalized = AssetDependencyScanner::NormalizeAssetReference(record.Reference);
            auto alias = aliasByTarget.find(normalized);
            if (alias == aliasByTarget.end() || alias->second.empty() || alias->second == record.Reference)
                continue;

            const std::string key = record.SourceFile.generic_string() + "|" + record.Reference + "|" + alias->second;
            if (!replacementKeys.insert(key).second)
                continue;

            AssetHygieneAction action;
            action.Type = AssetHygieneActionType::ReplacePathWithAlias;
            action.CanApply = true;
            action.Selected = false;
            action.Title = "Replace hardcoded asset path with alias";
            action.Detail = record.SourceFile.generic_string() + ": " + record.Reference + " -> " + alias->second;
            action.SourceFile = record.SourceFile;
            action.SearchText = record.Reference;
            action.ReplacementText = alias->second;
            m_HygieneActions.push_back(std::move(action));
        }

        const size_t selectedCount = std::count_if(m_HygieneActions.begin(), m_HygieneActions.end(),
            [](const AssetHygieneAction& action) { return action.Selected && action.CanApply; });
        m_HygieneActionStatus = "Generated " + std::to_string(m_HygieneActions.size())
            + " hygiene action(s), " + std::to_string(selectedCount) + " selected.";
    }

    bool ProjectHealthPanel::ApplySelectedHygieneActions()
    {
        const std::filesystem::path projectRoot = AssetPath::GetProjectRoot();
        size_t applied = 0;
        size_t failed = 0;
        std::string firstError;

        for (AssetHygieneAction& action : m_HygieneActions)
        {
            if (!action.Selected || !action.CanApply)
                continue;

            std::string error;
            bool ok = false;
            switch (action.Type)
            {
            case AssetHygieneActionType::ArchiveUnusedAsset:
            case AssetHygieneActionType::ArchiveDuplicateAsset:
                ok = MoveAssetToArchive(projectRoot, action, &error);
                break;
            case AssetHygieneActionType::ReplacePathWithAlias:
                ok = ReplaceTextInProjectFile(projectRoot, action, &error);
                break;
            case AssetHygieneActionType::ReviewDuplicateAsset:
                ok = false;
                error = "Review-only duplicate action cannot be applied.";
                break;
            }

            if (ok)
            {
                ++applied;
                action.Selected = false;
            }
            else
            {
                ++failed;
                if (firstError.empty())
                    firstError = error;
            }
        }

        Refresh();
        BuildHygieneCleanupPlan();
        m_HygieneActionStatus = "Applied " + std::to_string(applied) + " hygiene action(s).";
        if (failed > 0)
            m_HygieneActionStatus += " " + std::to_string(failed) + " failed. " + firstError;
        return failed == 0;
    }

    void ProjectHealthPanel::OnImGuiRender()
    {
        if (!m_Open)
            return;

        if (!EditorFloatingWindow::Begin(EditorLocale::Text("Project Health", "项目健康检查"), &m_Open, 0, { 1120.0f, 720.0f }))
        {
            EditorFloatingWindow::End();
            return;
        }

        const size_t issueCount = m_Report.MissingReferences.size()
            + m_Report.MissingSceneTransitions.size()
            + m_SourceReport.MissingFromProject.size()
            + m_SourceReport.StaleProjectEntries.size()
            + m_HygieneReport.DuplicateGroups.size()
            + m_HygieneReport.AliasIssues.size();
        EditorWidgets::PanelHeader(EditorLocale::Text("Project Health", "项目健康检查"), "Package dependency, asset hygiene, registry, and source/project sync validation.");
        EditorWidgets::StatusBadge(issueCount == 0 ? "Ready" : "Needs Attention",
            issueCount == 0 ? EditorWidgets::StatusKind::Success : EditorWidgets::StatusKind::Error);
        ImGui::SameLine();
        EditorWidgets::StatusBadge((std::to_string(m_Report.IncludedAssets.size()) + " packed assets").c_str(), EditorWidgets::StatusKind::Info);
        ImGui::SameLine();
        EditorWidgets::StatusBadge((std::to_string(m_Report.Warnings.size()) + " warning(s)").c_str(),
            m_Report.Warnings.empty() ? EditorWidgets::StatusKind::Neutral : EditorWidgets::StatusKind::Warning);
        ImGui::SameLine();
        EditorWidgets::StatusBadge((std::to_string(m_HygieneReport.DuplicateGroups.size()) + " duplicate group(s)").c_str(),
            m_HygieneReport.DuplicateGroups.empty() ? EditorWidgets::StatusKind::Neutral : EditorWidgets::StatusKind::Warning);
        ImGui::SameLine();
        EditorWidgets::StatusBadge((std::to_string(m_HygieneReport.HardcodedAssetPaths.size()) + " hardcoded path(s)").c_str(),
            m_HygieneReport.HardcodedAssetPaths.empty() ? EditorWidgets::StatusKind::Neutral : EditorWidgets::StatusKind::Warning);
        ImGui::SameLine();
        EditorFloatingWindow::DrawToggleButton(EditorLocale::Text("Project Health", "项目健康检查"));

        EditorWidgets::SectionHeader(EditorLocale::Text("Scan Scope", "扫描范围"), "The startup scene defines the package dependency closure.");
        EditorWidgets::InputString(EditorLocale::Text("Startup Scene", "启动场景"), m_StartupScene, 384);
        ImGui::Checkbox(EditorLocale::Text("Enable C# Script Assets", "启用 C# 脚本资源"), &m_EnableScripts);
        ImGui::SameLine();
        ImGui::Checkbox(EditorLocale::Text("Scan Unused Assets", "扫描未使用资源"), &m_IncludeUnusedAssets);

        if (ImGui::Button(EditorLocale::Text("Refresh", "刷新")))
            Refresh();
        ImGui::SameLine();
        EditorWidgets::InlineStatus(m_Status, issueCount == 0 ? EditorWidgets::StatusKind::Success : EditorWidgets::StatusKind::Warning);

        EditorWidgets::SectionHeader(EditorLocale::Text("Summary", "摘要"));
        DrawSummary();
        ImGui::Separator();

        if (ImGui::BeginTabBar("ProjectHealthTabs"))
        {
            if (ImGui::BeginTabItem(EditorLocale::Text("Missing", "缺失引用")))
            {
                DrawMissingReferences();
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Asset Registry", "资源注册表")))
            {
                DrawAssetRegistry();
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Packed Assets", "打包资源")))
            {
                DrawAssetList("PackedAssetTable", m_Report.IncludedAssets);
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Scene Links", "场景链接")))
            {
                DrawSceneTransitions();
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Unused Assets", "未使用资源")))
            {
                DrawAssetList("UnusedAssetTable", m_Report.UnusedAssets);
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Parsed Text", "解析文本")))
            {
                DrawAssetList("ParsedTextAssetTable", m_Report.ParsedTextAssets);
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Warnings", "警告")))
            {
                if (m_Report.Warnings.empty())
                {
                    EditorWidgets::EmptyState(EditorLocale::Text("No warnings.", "无警告。"), "The current scan did not find legacy commands or package risk notes.");
                }
                else
                {
                    for (const std::string& warning : m_Report.Warnings)
                        ImGui::BulletText("%s", warning.c_str());
                }
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Asset Hygiene", "资源卫生")))
            {
                DrawAssetHygiene();
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Alias Manifest", "别名清单")))
            {
                DrawAliasManifestEditor();
                ImGui::EndTabItem();
            }
            if (ImGui::BeginTabItem(EditorLocale::Text("Source Sync", "源码同步")))
            {
                DrawSourceSync();
                ImGui::EndTabItem();
            }
            ImGui::EndTabBar();
        }

        EditorFloatingWindow::End();
    }

    void ProjectHealthPanel::DrawSummary() const
    {
        SummaryLine(EditorLocale::Text("Packed Assets", "打包资源"), m_Report.IncludedAssets.size());
        SummaryLine("Packed Source Size", FormatBytes(m_Report.IncludedBytes));
        SummaryLine("Packable Assets", m_Report.PackableAssetCount);
        SummaryLine("Packable Source Size", FormatBytes(m_Report.PackableBytes));
        SummaryLine(EditorLocale::Text("Unused Assets", "未使用资源"), m_Report.UnusedAssets.size());
        SummaryLine("Parsed Text Assets", m_Report.ParsedTextAssets.size());
        SummaryLine("Scene Transitions", m_Report.SceneTransitions.size());
        SummaryLine("Missing Scene Transitions", m_Report.MissingSceneTransitions.size());
        SummaryLine(EditorLocale::Text("Missing References", "缺失引用"), m_Report.MissingReferences.size());
        SummaryLine("Asset Registry Assets", AssetRegistry::Get().GetAssetCount());
        SummaryLine("Asset Registry References", AssetRegistry::Get().GetReferenceCount());
        SummaryLine(EditorLocale::Text("Warnings", "警告"), m_Report.Warnings.size());
        SummaryLine("Duplicate Groups", m_HygieneReport.DuplicateGroups.size());
        SummaryLine("Duplicate Extra Assets", m_HygieneReport.DuplicateExtraAssetCount);
        SummaryLine("Alias Issues", m_HygieneReport.AliasIssues.size());
        SummaryLine("Hardcoded Asset Paths", m_HygieneReport.HardcodedAssetPaths.size());
        SummaryLine("Source Files", m_SourceReport.ScannedSourceFiles);
        SummaryLine("Project Entries", m_SourceReport.ScannedProjectEntries);
        SummaryLine("Source Sync Issues",
            m_SourceReport.MissingFromProject.size() + m_SourceReport.StaleProjectEntries.size());
    }

    void ProjectHealthPanel::DrawAssetRegistry() const
    {
        const auto& registry = AssetRegistry::Get();
        SummaryLine("Registered Assets", registry.GetAssetCount());
        SummaryLine("Reference Edges", registry.GetReferenceCount());

        ImGui::Spacing();
        if (ImGui::BeginTable("AssetRegistryTable", 5,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollY,
            ImVec2(0, 420)))
        {
            ImGui::TableSetupColumn("Type");
            ImGui::TableSetupColumn("UUID");
            ImGui::TableSetupColumn(EditorLocale::Text("Asset", "资源"));
            ImGui::TableSetupColumn(EditorLocale::Text("Refs", "引用数"));
            ImGui::TableSetupColumn(EditorLocale::Text("Used By", "被引用"));
            ImGui::TableHeadersRow();

            const auto& assets = registry.GetAssets();
            const size_t rowCount = std::min<size_t>(assets.size(), 1000);
            for (size_t i = 0; i < rowCount; ++i)
            {
                const EditorAssetMetadata& metadata = assets[i];
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                ImGui::TextUnformatted(AssetRegistry::KindToString(metadata.Kind).c_str());
                ImGui::TableSetColumnIndex(1);
                ImGui::Text("%llu", static_cast<unsigned long long>(static_cast<uint64_t>(metadata.ID)));
                ImGui::TableSetColumnIndex(2);
                ImGui::TextWrapped("%s", metadata.RelativePath.c_str());
                ImGui::TableSetColumnIndex(3);
                ImGui::Text("%zu", metadata.References.size());
                ImGui::TableSetColumnIndex(4);
                ImGui::Text("%zu", metadata.ReferencedBy.size());
            }

            ImGui::EndTable();
        }
    }

    void ProjectHealthPanel::DrawMissingReferences() const
    {
        if (m_Report.MissingReferences.empty())
        {
            EditorWidgets::EmptyState(EditorLocale::Text("No missing asset references found.", "未发现缺失的资源引用。"), "All scanned scene, YAML, script, and manifest references resolve.");
            return;
        }

        if (ImGui::BeginTable("MissingReferenceTable", 2,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable))
        {
            ImGui::TableSetupColumn("Reference");
            ImGui::TableSetupColumn("Source");
            ImGui::TableHeadersRow();

            for (const AssetReferenceRecord& record : m_Report.MissingReferences)
            {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                ImGui::TextWrapped("%s", record.Reference.c_str());
                ImGui::TableSetColumnIndex(1);
                ImGui::TextWrapped("%s", record.SourceAsset.empty() ? "(startup/builtin)" : record.SourceAsset.c_str());
            }

            ImGui::EndTable();
        }
    }

    void ProjectHealthPanel::DrawSceneTransitions() const
    {
        if (!m_Report.MissingSceneTransitions.empty())
        {
            ImGui::TextColored(ImVec4(1.0f, 0.35f, 0.25f, 1.0f),
                "Missing scene transition target(s) found.");
            if (ImGui::BeginTable("MissingSceneTransitionTable", 2,
                ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable))
            {
                ImGui::TableSetupColumn("Scene");
                ImGui::TableSetupColumn("Source");
                ImGui::TableHeadersRow();

                for (const AssetReferenceRecord& record : m_Report.MissingSceneTransitions)
                {
                    ImGui::TableNextRow();
                    ImGui::TableSetColumnIndex(0);
                    ImGui::TextWrapped("%s", record.Reference.c_str());
                    ImGui::TableSetColumnIndex(1);
                    ImGui::TextWrapped("%s", record.SourceAsset.empty() ? "(startup/builtin)" : record.SourceAsset.c_str());
                }

                ImGui::EndTable();
            }
            ImGui::Separator();
        }

        if (m_Report.SceneTransitions.empty())
        {
            EditorWidgets::EmptyState("No scene transition commands found.", "Parsed text assets did not declare scene/newgame/loadgame targets.");
            return;
        }

        if (ImGui::BeginTable("SceneTransitionTable", 2,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable))
        {
            ImGui::TableSetupColumn("Scene");
            ImGui::TableSetupColumn("Source");
            ImGui::TableHeadersRow();

            for (const AssetReferenceRecord& record : m_Report.SceneTransitions)
            {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                ImGui::TextWrapped("%s", record.Reference.c_str());
                ImGui::TableSetColumnIndex(1);
                ImGui::TextWrapped("%s", record.SourceAsset.empty() ? "(startup/builtin)" : record.SourceAsset.c_str());
            }

            ImGui::EndTable();
        }
    }

    void ProjectHealthPanel::DrawAssetHygiene()
    {
        SummaryLine("Duplicate Groups", m_HygieneReport.DuplicateGroups.size());
        SummaryLine("Duplicate Extra Assets", m_HygieneReport.DuplicateExtraAssetCount);
        SummaryLine("Duplicate Extra Size", FormatBytes(m_HygieneReport.DuplicateExtraBytes));
        SummaryLine("Alias Issues", m_HygieneReport.AliasIssues.size());
        SummaryLine("Hardcoded Asset Paths", m_HygieneReport.HardcodedAssetPaths.size());
        SummaryLine(EditorLocale::Text("Unused Assets", "未使用资源"), m_Report.UnusedAssets.size());

        ImGui::Spacing();
        ImGui::Separator();
        ImGui::Spacing();

        if (!ImGui::BeginTabBar("AssetHygieneTabs"))
            return;

        if (ImGui::BeginTabItem(EditorLocale::Text("Cleanup Plan", "清理计划")))
        {
            DrawHygieneCleanupPlan();
            ImGui::EndTabItem();
        }

        if (ImGui::BeginTabItem(EditorLocale::Text("Duplicates", "重复资源")))
        {
            if (m_HygieneReport.DuplicateGroups.empty())
            {
                EditorWidgets::EmptyState("No duplicate binary asset hashes found.", "Packable binary assets with matching size and content hash are unique.");
            }
            else
            {
                for (size_t i = 0; i < m_HygieneReport.DuplicateGroups.size(); ++i)
                {
                    const AssetDuplicateGroup& group = m_HygieneReport.DuplicateGroups[i];
                    const std::string label = "Group " + std::to_string(i + 1)
                        + "  |  " + std::to_string(group.Assets.size()) + " files"
                        + "  |  " + FormatBytes(group.SizeBytes)
                        + " each  |  " + group.Hash;
                    if (ImGui::TreeNodeEx(label.c_str(), ImGuiTreeNodeFlags_DefaultOpen))
                    {
                        for (const auto& asset : group.Assets)
                            ImGui::BulletText("%s", asset.generic_string().c_str());
                        ImGui::TreePop();
                    }
                }
            }
            ImGui::EndTabItem();
        }

        if (ImGui::BeginTabItem(EditorLocale::Text("Largest Files", "最大文件")))
        {
            if (m_HygieneReport.LargestAssets.empty())
            {
                ImGui::TextDisabled("No packable binary assets found.");
            }
            else
            {
                const size_t maxRows = std::min<size_t>(m_HygieneReport.LargestAssets.size(), 100);
                if (m_HygieneReport.LargestAssets.size() > maxRows)
                    ImGui::TextDisabled("Showing largest %zu of %zu packable binary assets.", maxRows, m_HygieneReport.LargestAssets.size());

                if (ImGui::BeginTable("AssetHygieneLargeFileTable", 4,
                    ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollY,
                    ImVec2(0, 420)))
                {
                    ImGui::TableSetupColumn("Size");
                    ImGui::TableSetupColumn(EditorLocale::Text("Packed", "已打包"));
                    ImGui::TableSetupColumn("Unused");
                    ImGui::TableSetupColumn(EditorLocale::Text("Asset", "资源"));
                    ImGui::TableHeadersRow();

                    for (size_t i = 0; i < maxRows; ++i)
                    {
                        const AssetSizeRecord& record = m_HygieneReport.LargestAssets[i];
                        ImGui::TableNextRow();
                        ImGui::TableSetColumnIndex(0);
                        ImGui::TextUnformatted(FormatBytes(record.SizeBytes).c_str());
                        ImGui::TableSetColumnIndex(1);
                        ImGui::TextUnformatted(record.Packed ? "yes" : "no");
                        ImGui::TableSetColumnIndex(2);
                        ImGui::TextUnformatted(record.Unused ? "yes" : "no");
                        ImGui::TableSetColumnIndex(3);
                        ImGui::TextWrapped("%s", record.Asset.generic_string().c_str());
                    }

                    ImGui::EndTable();
                }
            }
            ImGui::EndTabItem();
        }

        if (ImGui::BeginTabItem(EditorLocale::Text("Aliases", "别名")))
        {
            if (m_HygieneReport.AliasIssues.empty())
            {
                EditorWidgets::EmptyState("No alias target issues found.", "All loaded content manifest aliases resolve into the current project.");
            }
            else if (ImGui::BeginTable("AssetHygieneAliasIssueTable", 3,
                ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollY,
                ImVec2(0, 420)))
            {
                ImGui::TableSetupColumn(EditorLocale::Text("Alias", "别名"));
                ImGui::TableSetupColumn(EditorLocale::Text("Target", "目标"));
                ImGui::TableSetupColumn(EditorLocale::Text("Issue", "问题"));
                ImGui::TableHeadersRow();

                for (const AssetAliasIssue& issue : m_HygieneReport.AliasIssues)
                {
                    ImGui::TableNextRow();
                    ImGui::TableSetColumnIndex(0);
                    ImGui::TextWrapped("%s", issue.Alias.c_str());
                    ImGui::TableSetColumnIndex(1);
                    ImGui::TextWrapped("%s", issue.Target.c_str());
                    ImGui::TableSetColumnIndex(2);
                    ImGui::TextWrapped("%s", issue.Issue.c_str());
                }

                ImGui::EndTable();
            }
            ImGui::EndTabItem();
        }

        if (ImGui::BeginTabItem(EditorLocale::Text("Source Paths", "源码路径")))
        {
            if (m_HygieneReport.HardcodedAssetPaths.empty())
            {
                EditorWidgets::EmptyState("No hardcoded asset path references found.", "Source and tool files did not contain literal assets/... paths.");
            }
            else
            {
                const size_t maxRows = std::min<size_t>(m_HygieneReport.HardcodedAssetPaths.size(), 500);
                if (m_HygieneReport.HardcodedAssetPaths.size() > maxRows)
                    ImGui::TextDisabled("Showing first %zu of %zu hardcoded asset path references.", maxRows, m_HygieneReport.HardcodedAssetPaths.size());

                if (ImGui::BeginTable("AssetHygieneSourcePathTable", 2,
                    ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollY,
                    ImVec2(0, 420)))
                {
                    ImGui::TableSetupColumn(EditorLocale::Text("Source File", "源文件"));
                    ImGui::TableSetupColumn("Reference");
                    ImGui::TableHeadersRow();

                    for (size_t i = 0; i < maxRows; ++i)
                    {
                        const HardcodedAssetPathRecord& record = m_HygieneReport.HardcodedAssetPaths[i];
                        ImGui::TableNextRow();
                        ImGui::TableSetColumnIndex(0);
                        ImGui::TextWrapped("%s", record.SourceFile.generic_string().c_str());
                        ImGui::TableSetColumnIndex(1);
                        ImGui::TextWrapped("%s", record.Reference.c_str());
                    }

                    ImGui::EndTable();
                }
            }
            ImGui::EndTabItem();
        }

        ImGui::EndTabBar();
    }

    void ProjectHealthPanel::DrawHygieneCleanupPlan()
    {
        if (ImGui::Button(EditorLocale::Text("Generate Cleanup Plan", "生成清理计划")))
            BuildHygieneCleanupPlan();

        ImGui::SameLine();
        if (ImGui::Button(EditorLocale::Text("Select Safe Archive Actions", "选择安全归档项")))
        {
            for (AssetHygieneAction& action : m_HygieneActions)
            {
                action.Selected = action.CanApply
                    && (action.Type == AssetHygieneActionType::ArchiveUnusedAsset
                        || action.Type == AssetHygieneActionType::ArchiveDuplicateAsset);
            }
        }

        ImGui::SameLine();
        if (ImGui::Button(EditorLocale::Text("Clear Selection", "清空选择")))
        {
            for (AssetHygieneAction& action : m_HygieneActions)
                action.Selected = false;
        }

        const size_t selectedCount = std::count_if(m_HygieneActions.begin(), m_HygieneActions.end(),
            [](const AssetHygieneAction& action) { return action.Selected && action.CanApply; });
        uintmax_t selectedBytes = 0;
        for (const AssetHygieneAction& action : m_HygieneActions)
        {
            if (action.Selected
                && action.CanApply
                && (action.Type == AssetHygieneActionType::ArchiveUnusedAsset
                    || action.Type == AssetHygieneActionType::ArchiveDuplicateAsset))
                selectedBytes += action.SizeBytes;
        }

        ImGui::SameLine();
        ImGui::BeginDisabled(selectedCount == 0);
        if (ImGui::Button(EditorLocale::Text("Apply Selected", "应用选中项")))
            ImGui::OpenPopup("Apply Hygiene Actions?");
        ImGui::EndDisabled();

        if (ImGui::BeginPopupModal("Apply Hygiene Actions?", nullptr, ImGuiWindowFlags_AlwaysAutoResize))
        {
            ImGui::TextWrapped("Apply %zu selected action(s)? Archive actions move files into assets/.wheatear/archive. Alias actions edit text files in place.", selectedCount);
            ImGui::Spacing();
            if (ImGui::Button("Apply"))
            {
                ApplySelectedHygieneActions();
                ImGui::CloseCurrentPopup();
            }
            ImGui::SameLine();
            if (ImGui::Button("Cancel"))
                ImGui::CloseCurrentPopup();
            ImGui::EndPopup();
        }

        EditorWidgets::InlineStatus(m_HygieneActionStatus.empty()
                ? "Generate a cleanup plan from the latest scan before applying changes."
                : m_HygieneActionStatus,
            m_HygieneActionStatus.find("failed") != std::string::npos ? EditorWidgets::StatusKind::Error : EditorWidgets::StatusKind::Info);
        SummaryLine("Plan Actions", m_HygieneActions.size());
        SummaryLine("Selected Actions", selectedCount);
        SummaryLine("Selected Archive Size", FormatBytes(selectedBytes));

        if (m_HygieneActions.empty())
        {
            EditorWidgets::EmptyState("No cleanup plan generated.", "Click Generate Cleanup Plan after refreshing Project Health.");
            return;
        }

        if (ImGui::BeginTable("AssetHygieneCleanupPlanTable", 6,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollY,
            ImVec2(0, 440)))
        {
            ImGui::TableSetupColumn("Apply", ImGuiTableColumnFlags_WidthFixed, 52.0f);
            ImGui::TableSetupColumn("Type", ImGuiTableColumnFlags_WidthFixed, 130.0f);
            ImGui::TableSetupColumn("Size", ImGuiTableColumnFlags_WidthFixed, 88.0f);
            ImGui::TableSetupColumn("Action");
            ImGui::TableSetupColumn("Source");
            ImGui::TableSetupColumn("Destination / Replacement");
            ImGui::TableHeadersRow();

            for (size_t i = 0; i < m_HygieneActions.size(); ++i)
            {
                AssetHygieneAction& action = m_HygieneActions[i];
                ImGui::PushID(static_cast<int>(i));
                ImGui::TableNextRow();

                ImGui::TableSetColumnIndex(0);
                ImGui::BeginDisabled(!action.CanApply);
                ImGui::Checkbox("##selected", &action.Selected);
                ImGui::EndDisabled();

                ImGui::TableSetColumnIndex(1);
                ImGui::TextUnformatted(HygieneActionTypeName(action.Type));

                ImGui::TableSetColumnIndex(2);
                ImGui::TextUnformatted(action.SizeBytes > 0 ? FormatBytes(action.SizeBytes).c_str() : "-");

                ImGui::TableSetColumnIndex(3);
                ImGui::TextWrapped("%s", action.Title.c_str());
                if (!action.Detail.empty())
                    ImGui::TextDisabled("%s", action.Detail.c_str());

                ImGui::TableSetColumnIndex(4);
                if (!action.SourceAsset.empty())
                    ImGui::TextWrapped("%s", action.SourceAsset.generic_string().c_str());
                else
                    ImGui::TextWrapped("%s", action.SourceFile.generic_string().c_str());

                ImGui::TableSetColumnIndex(5);
                if (!action.DestinationAsset.empty())
                    ImGui::TextWrapped("%s", action.DestinationAsset.generic_string().c_str());
                else
                    ImGui::TextWrapped("%s -> %s", action.SearchText.c_str(), action.ReplacementText.c_str());

                ImGui::PopID();
            }

            ImGui::EndTable();
        }
    }

    void ProjectHealthPanel::DrawAliasManifestEditor()
    {
        EditorWidgets::SectionHeader(EditorLocale::Text("Alias Manifest", "别名清单"), "Edit content_manifest.yaml aliases used by runtime asset lookup.");

        ImGui::SetNextItemWidth(420.0f);
        EditorWidgets::InputString("Manifest", m_AliasManifestPath, 512);
        ImGui::SameLine();
        if (ImGui::Button("Load Manifest"))
            LoadAliasManifest();
        ImGui::SameLine();
        if (ImGui::Button("Save Manifest"))
            SaveAliasManifest();

        EditorGameplayShell::DrawDocumentStatus({
            EditorGameplayShell::DocumentKind::Asset,
            m_AliasManifestDocument.IsDirty(),
            m_AliasManifestDocument.IsParseValid(),
            m_AliasManifestPath,
            m_AliasStatus.empty() ? m_AliasManifestDocument.GetStatus() : m_AliasStatus
        });

        if (!m_AliasManifestDocument.IsParseValid())
        {
            EditorWidgets::InlineStatus("Manifest YAML parse failed. Fix the file before alias editing.", EditorWidgets::StatusKind::Error);
            return;
        }

        YAML::Node root = m_AliasManifestDocument.Root();
        std::vector<AliasManifestRow> rows = BuildAliasRows(root);
        if (m_SelectedAlias.empty() && !rows.empty())
            m_SelectedAlias = rows.front().Alias;

        const float listWidth = std::max(360.0f, ImGui::GetContentRegionAvail().x * 0.45f);
        ImGui::BeginChild("##AliasManifestRows", ImVec2(listWidth, 0.0f), true);
        if (rows.empty())
        {
            EditorWidgets::EmptyState("No aliases found.", "Add an alias below to start building the manifest.");
        }
        else if (ImGui::BeginTable("AliasManifestTable", 2,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable | ImGuiTableFlags_ScrollY,
            ImVec2(0, 420)))
        {
            ImGui::TableSetupColumn(EditorLocale::Text("Alias", "别名"));
            ImGui::TableSetupColumn(EditorLocale::Text("Target", "目标"));
            ImGui::TableHeadersRow();

            for (const AliasManifestRow& row : rows)
            {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                const std::string label = EditorWidgets::LabelWithId(row.Alias, "alias_manifest:" + row.Alias);
                if (ImGui::Selectable(label.c_str(), row.Alias == m_SelectedAlias, ImGuiSelectableFlags_SpanAllColumns))
                    m_SelectedAlias = row.Alias;
                ImGui::TableSetColumnIndex(1);
                ImGui::TextWrapped("%s", row.Target.c_str());
            }

            ImGui::EndTable();
        }

        ImGui::Separator();
        EditorWidgets::SectionHeader(EditorLocale::Text("Add Alias", "添加别名"));
        EditorWidgets::InputString(EditorLocale::Text("New Alias", "新别名"), m_NewAliasName, 256);
        EditorWidgets::DrawAssetReferenceField("New Target",
            m_NewAliasTarget,
            EditorWidgets::AssetReferenceKind::Any,
            512);
        const bool canAdd = !m_NewAliasName.empty() && !m_NewAliasTarget.empty();
        ImGui::BeginDisabled(!canAdd);
        if (ImGui::Button(EditorLocale::Text("Add Alias", "添加别名")) && canAdd)
        {
            if (SetAliasTarget(root, m_NewAliasName, m_NewAliasTarget))
            {
                m_SelectedAlias = m_NewAliasName;
                m_NewAliasName.clear();
                m_NewAliasTarget = "assets/";
                m_AliasManifestDocument.MarkDirty();
                m_AliasStatus = "Alias added.";
            }
        }
        ImGui::EndDisabled();
        ImGui::EndChild();

        ImGui::SameLine();
        ImGui::BeginChild("##AliasManifestDetails", ImVec2(0.0f, 0.0f), true);
        EditorWidgets::SectionHeader(EditorLocale::Text("Alias Details", "别名详情"), "Rename aliases or retarget them to project assets.");

        auto selected = std::find_if(rows.begin(), rows.end(), [&](const AliasManifestRow& row)
        {
            return row.Alias == m_SelectedAlias;
        });

        if (selected == rows.end())
        {
            EditorWidgets::EmptyState("Select an alias to edit.");
            ImGui::EndChild();
            return;
        }

        std::string alias = selected->Alias;
        std::string target = selected->Target;
        if (EditorWidgets::InputString(EditorLocale::Text("Alias", "别名"), alias, 256)
            && !alias.empty()
            && alias != selected->Alias)
        {
            RemoveAliasTarget(root, selected->Alias);
            SetAliasTarget(root, alias, target);
            m_SelectedAlias = alias;
            m_AliasManifestDocument.MarkDirty();
            m_AliasStatus = "Alias renamed.";
        }

        if (EditorWidgets::DrawAssetReferenceField(EditorLocale::Text("Target", "目标"),
            target,
            EditorWidgets::AssetReferenceKind::Any,
            512))
        {
            SetAliasTarget(root, m_SelectedAlias, target);
            m_AliasManifestDocument.MarkDirty();
            m_AliasStatus = "Alias target changed.";
        }

        const std::filesystem::path resolvedTarget = EditorWidgets::ResolveProjectAsset(target);
        if (!target.empty())
        {
            const bool exists = !resolvedTarget.empty() && std::filesystem::exists(resolvedTarget);
            EditorWidgets::StatusBadge(exists ? "Target exists" : "Target missing",
                exists ? EditorWidgets::StatusKind::Success : EditorWidgets::StatusKind::Error);
            if (!resolvedTarget.empty())
                ImGui::TextDisabled("%s", resolvedTarget.generic_string().c_str());
        }

        ImGui::Separator();
        if (ImGui::Button(EditorLocale::Text("Delete Alias", "删除别名")))
        {
            if (RemoveAliasTarget(root, m_SelectedAlias))
            {
                m_SelectedAlias.clear();
                m_AliasManifestDocument.MarkDirty();
                m_AliasStatus = "Alias deleted.";
            }
        }
        ImGui::EndChild();
    }

    void ProjectHealthPanel::DrawAssetList(const char* tableId,
        const std::vector<std::filesystem::path>& assets,
        size_t maxRows) const
    {
        if (assets.empty())
        {
            ImGui::TextDisabled("No assets in this list.");
            return;
        }

        if (assets.size() > maxRows)
            ImGui::TextDisabled("Showing first %zu of %zu rows.", maxRows, assets.size());

        if (ImGui::BeginTable(tableId, 1,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable))
        {
            ImGui::TableSetupColumn(EditorLocale::Text("Asset", "资源"));
            ImGui::TableHeadersRow();

            const size_t rowCount = std::min(maxRows, assets.size());
            for (size_t i = 0; i < rowCount; ++i)
            {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                const std::string path = assets[i].generic_string();
                ImGui::TextWrapped("%s", path.c_str());
            }

            ImGui::EndTable();
        }
    }

    void ProjectHealthPanel::DrawSourceSync() const
    {
        if (m_SourceReport.Healthy())
        {
            ImGui::TextDisabled("Source trees and Visual Studio project files are in sync.");
            return;
        }

        if (ImGui::BeginTable("ProjectSourceSyncTable", 3,
            ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg | ImGuiTableFlags_Resizable))
        {
            ImGui::TableSetupColumn("Type");
            ImGui::TableSetupColumn("Project");
            ImGui::TableSetupColumn("File");
            ImGui::TableHeadersRow();

            for (const ProjectSourceRecord& record : m_SourceReport.MissingFromProject)
            {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                ImGui::TextUnformatted("Missing From Project");
                ImGui::TableSetColumnIndex(1);
                ImGui::TextUnformatted(record.ProjectName.c_str());
                ImGui::TableSetColumnIndex(2);
                const std::string file = record.File.generic_string();
                ImGui::TextWrapped("%s", file.c_str());
            }

            for (const ProjectSourceRecord& record : m_SourceReport.StaleProjectEntries)
            {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0);
                ImGui::TextUnformatted("Stale Project Entry");
                ImGui::TableSetColumnIndex(1);
                ImGui::TextUnformatted(record.ProjectName.c_str());
                ImGui::TableSetColumnIndex(2);
                const std::string file = record.File.generic_string();
                ImGui::TextWrapped("%s", file.c_str());
            }

            ImGui::EndTable();
        }
    }

} // namespace Wheatear
