#include "wepch.h"
#include "AssetAliasManifestEditorPanel.h"

#include "Editor/EditorContentPickers.h"
#include "Editor/EditorLocale.h"
#include "Editor/GameplayEditorShell.h"
#include "Editor/EditorWidgets.h"
#include "Wheatear/Assets/AssetAliasRegistry.h"
#include "Wheatear/Assets/AssetPath.h"

#include <imgui/imgui.h>
#include <yaml-cpp/yaml.h>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <sstream>
#include <string>
#include <vector>

namespace Wheatear {

    namespace {

        constexpr const char* AliasManifestHeader =
            "# Generated by Wheatear Asset Alias Manifest Editor.\n"
            "# Runtime systems read this file through AssetAliasRegistry.\n\n";

        struct AliasRow
        {
            std::string Alias;
            std::string Target;
        };

        std::vector<std::string> SplitAliasPath(const std::string& alias)
        {
            std::vector<std::string> parts;
            std::stringstream stream(alias);
            std::string part;
            while (std::getline(stream, part, '.'))
            {
                if (!part.empty())
                    parts.push_back(part);
            }
            return parts;
        }

        std::string ScalarText(const YAML::Node& node)
        {
            if (!node || !node.IsDefined() || node.IsNull())
                return {};
            try
            {
                return node.as<std::string>("");
            }
            catch (...)
            {
                return {};
            }
        }

        void FlattenAliases(const YAML::Node& node,
            const std::string& prefix,
            std::vector<AliasRow>& rows)
        {
            if (!node)
                return;

            if (node.IsMap())
            {
                for (const auto& entry : node)
                {
                    if (!entry.first.IsScalar())
                        continue;
                    const std::string key = entry.first.as<std::string>("");
                    if (key.empty())
                        continue;
                    const std::string nextPrefix = prefix.empty() ? key : prefix + "." + key;
                    FlattenAliases(entry.second, nextPrefix, rows);
                }
                return;
            }

            if (!prefix.empty() && node.IsScalar())
                rows.push_back({ prefix, ScalarText(node) });
        }

        std::vector<AliasRow> BuildAliasRows(const YAML::Node& root)
        {
            std::vector<AliasRow> rows;
            YAML::Node aliases = root["aliases"];
            if (!aliases || !aliases.IsMap())
                aliases = root;
            FlattenAliases(aliases, {}, rows);
            std::sort(rows.begin(), rows.end(), [](const AliasRow& left, const AliasRow& right)
            {
                return left.Alias < right.Alias;
            });
            return rows;
        }

        YAML::Node AliasRoot(YAML::Node root)
        {
            YAML::Node aliases = root["aliases"];
            if (!aliases || !aliases.IsMap())
            {
                root["aliases"] = YAML::Node(YAML::NodeType::Map);
                aliases = root["aliases"];
            }
            return aliases;
        }

        bool SetAliasTarget(YAML::Node root,
            const std::string& alias,
            const std::string& target)
        {
            const std::vector<std::string> parts = SplitAliasPath(alias);
            if (parts.empty() || target.empty())
                return false;

            YAML::Node cursor = AliasRoot(root);
            for (size_t i = 0; i + 1 < parts.size(); ++i)
            {
                YAML::Node child = cursor[parts[i]];
                if (!child || !child.IsMap())
                    cursor[parts[i]] = YAML::Node(YAML::NodeType::Map);
                cursor = cursor[parts[i]];
            }

            cursor[parts.back()] = target;
            return true;
        }

        bool RemoveAliasTarget(YAML::Node root, const std::string& alias)
        {
            const std::vector<std::string> parts = SplitAliasPath(alias);
            if (parts.empty())
                return false;

            YAML::Node cursor = AliasRoot(root);
            for (size_t i = 0; i + 1 < parts.size(); ++i)
            {
                cursor = cursor[parts[i]];
                if (!cursor || !cursor.IsMap())
                    return false;
            }
            return cursor.remove(parts.back());
        }

        bool TargetExists(const std::string& target)
        {
            if (target.empty())
                return false;
            return EditorWidgets::ProjectAssetExists(target)
                || AssetAliasRegistry::Has(target);
        }

        std::string ToLowerCopy(std::string value)
        {
            std::transform(value.begin(), value.end(), value.begin(), [](unsigned char c)
            {
                return static_cast<char>(std::tolower(c));
            });
            return value;
        }

        bool ReplaceAllExact(std::string& text, const std::string& from, const std::string& to, size_t* count = nullptr)
        {
            if (from.empty() || from == to)
                return false;

            bool changed = false;
            size_t replacements = 0;
            size_t position = 0;
            while ((position = text.find(from, position)) != std::string::npos)
            {
                text.replace(position, from.size(), to);
                position += to.size();
                changed = true;
                ++replacements;
            }

            if (count)
                *count = replacements;
            return changed;
        }

        bool IsReferenceTextFile(const std::filesystem::path& path)
        {
            const std::string extension = ToLowerCopy(path.extension().generic_string());
            return extension == ".yaml"
                || extension == ".yml"
                || extension == ".json"
                || extension == ".wt"
                || extension == ".wts"
                || extension == ".vn"
                || extension == ".txt"
                || extension == ".md"
                || extension == ".ini"
                || extension == ".cfg"
                || extension == ".lua"
                || extension == ".cs"
                || extension == ".cpp"
                || extension == ".c"
                || extension == ".cc"
                || extension == ".h"
                || extension == ".hpp"
                || extension == ".inl";
        }

        bool ShouldSkipReferencePath(const std::filesystem::path& relativePath)
        {
            const std::string path = ToLowerCopy(relativePath.generic_string());
            return path.empty()
                || path.rfind(".git/", 0) == 0
                || path.rfind(".vs/", 0) == 0
                || path.rfind("bin/", 0) == 0
                || path.rfind("bin-int/", 0) == 0
                || path.rfind("vendor/", 0) == 0
                || path.rfind("wheateareditor/assets/.wheatear/archive/", 0) == 0
                || path.find("/.git/") != std::string::npos
                || path.find("/bin/") != std::string::npos
                || path.find("/bin-int/") != std::string::npos
                || path.find("/vendor/") != std::string::npos
                || path.find("/assets/.wheatear/archive/") != std::string::npos;
        }

        struct ReferenceReplacementSummary
        {
            size_t FilesVisited = 0;
            size_t FilesChanged = 0;
            size_t Occurrences = 0;
            std::string FirstChangedFile;
            std::string Error;
        };

        ReferenceReplacementSummary ReplaceProjectReferences(
            const std::string& searchText,
            const std::string& replacementText,
            const std::filesystem::path& manifestPath,
            bool dryRun)
        {
            ReferenceReplacementSummary summary;
            if (searchText.empty() || replacementText.empty())
            {
                summary.Error = "Search and replacement must both be set.";
                return summary;
            }
            if (searchText == replacementText)
            {
                summary.Error = "Search and replacement are identical.";
                return summary;
            }

            const std::filesystem::path projectRoot = AssetPath::GetProjectRoot();
            const std::filesystem::path workspaceRoot = projectRoot.parent_path();
            const std::filesystem::path manifestAbsolute = AssetPath::Resolve(manifestPath).lexically_normal();
            if (workspaceRoot.empty() || !std::filesystem::exists(workspaceRoot))
            {
                summary.Error = "Workspace root is missing.";
                return summary;
            }

            std::error_code iteratorError;
            for (const auto& entry : std::filesystem::recursive_directory_iterator(workspaceRoot, iteratorError))
            {
                if (iteratorError)
                    break;
                if (!entry.is_regular_file())
                    continue;

                std::error_code relativeError;
                const std::filesystem::path relative = std::filesystem::relative(entry.path(), workspaceRoot, relativeError);
                if (relativeError || ShouldSkipReferencePath(relative) || !IsReferenceTextFile(entry.path()))
                    continue;

                if (entry.path().lexically_normal() == manifestAbsolute)
                    continue;

                ++summary.FilesVisited;
                std::string text;
                if (!EditorWidgets::ReadFileText(entry.path(), text))
                    continue;

                size_t replacements = 0;
                if (!ReplaceAllExact(text, searchText, replacementText, &replacements))
                    continue;

                summary.Occurrences += replacements;
                ++summary.FilesChanged;
                if (summary.FirstChangedFile.empty())
                    summary.FirstChangedFile = relative.generic_string();

                if (!dryRun && !EditorWidgets::WriteFileText(entry.path(), text))
                {
                    summary.Error = "Failed to write " + relative.generic_string();
                    return summary;
                }
            }

            if (iteratorError)
                summary.Error = "Scan failed: " + iteratorError.message();
            return summary;
        }

    } // namespace

    void AssetAliasManifestEditorPanel::Open(const EditorToolContext&)
    {
        m_Open = true;
        if (!m_Document.IsLoaded())
            Load();
    }

    void AssetAliasManifestEditorPanel::Load()
    {
        m_Document.SetSourcePath(m_SourcePath);
        m_Document.SetWriteDestination(EditorDocuments::DocumentWriteDestination::ProjectRoot);
        m_Document.Load();
        m_Status = m_Document.GetStatus();
        m_SelectedAlias.clear();
    }

    void AssetAliasManifestEditorPanel::Save()
    {
        if (m_Document.Save(AliasManifestHeader))
        {
            AssetAliasRegistry::Reload(m_SourcePath);
            m_Status = "Alias manifest saved and registry reloaded.";
        }
        else
        {
            m_Status = m_Document.GetStatus();
        }
    }

    void AssetAliasManifestEditorPanel::OnImGuiRender()
    {
        if (!m_Open)
            return;

        ImGui::Begin("Asset Alias / Manifest Editor", &m_Open);

        EditorGameplayShell::DocumentStatus documentStatus;
        documentStatus.Kind = EditorGameplayShell::DocumentKind::Asset;
        documentStatus.Dirty = m_Document.IsDirty();
        documentStatus.Valid = m_Document.IsParseValid();
        documentStatus.SourcePath = m_SourcePath;
        documentStatus.Status = m_Status.empty() ? m_Document.GetStatus() : m_Status;

        bool reload = false;
        if (EditorGameplayShell::DrawAssetToolbar(documentStatus,
            "Save Asset",
            "Reload Asset",
            &reload))
            Save();
        if (reload)
            Load();

        if (!m_Document.IsParseValid())
        {
            EditorWidgets::EmptyState("Manifest cannot be edited.",
                "Fix the YAML parse error before changing aliases.");
            EditorWidgets::InlineStatus(m_Document.GetStatus(), EditorWidgets::StatusKind::Error);
            ImGui::End();
            return;
        }

        YAML::Node root = m_Document.Root();
        const std::vector<AliasRow> rows = BuildAliasRows(root);
        if (m_SelectedAlias.empty() && !rows.empty())
            m_SelectedAlias = rows.front().Alias;

        const float listWidth = std::max(240.0f, ImGui::GetContentRegionAvail().x * 0.32f);
        ImGui::BeginChild("##AliasManifestList", ImVec2(listWidth, 0.0f), true);
        EditorWidgets::SectionHeader(
            EditorLocale::Text("Aliases", "别名"),
            EditorLocale::Text("Names used by gameplay assets and runtime systems.", "Gameplay 资产和运行时系统使用的稳定名称。"));
        if (rows.empty())
        {
            EditorWidgets::EmptyState(
                EditorLocale::Text("No aliases yet.", "还没有别名。"),
                EditorLocale::Text("Add an alias below to create a stable content reference.", "在下方添加别名来创建稳定内容引用。"));
        }
        else
        {
            for (const AliasRow& row : rows)
            {
                const std::string label = EditorWidgets::LabelWithId(row.Alias,
                    "alias_manifest:" + row.Alias);
                if (ImGui::Selectable(label.c_str(), row.Alias == m_SelectedAlias))
                    m_SelectedAlias = row.Alias;
                if (ImGui::IsItemHovered())
                    ImGui::SetTooltip("%s", row.Target.c_str());
            }
        }

        ImGui::Separator();
        EditorWidgets::SectionHeader(EditorLocale::Text("Add Alias", "添加别名"));
        EditorWidgets::InputString("New Alias", m_NewAliasName, 256);
        EditorContentPickers::DrawAssetField("New Target",
            m_NewAliasTarget,
            EditorWidgets::AssetReferenceKind::Any,
            512);
        const bool canAdd = !m_NewAliasName.empty() && !m_NewAliasTarget.empty();
        ImGui::BeginDisabled(!canAdd);
        if (ImGui::Button("Add Alias"))
        {
            if (SetAliasTarget(root, m_NewAliasName, m_NewAliasTarget))
            {
                m_SelectedAlias = m_NewAliasName;
                m_NewAliasName.clear();
                m_NewAliasTarget = "assets/";
                m_Document.MarkDirty();
                m_Status = "Alias added.";
            }
        }
        ImGui::EndDisabled();
        ImGui::EndChild();

        ImGui::SameLine();
        ImGui::BeginChild("##AliasManifestDetails", ImVec2(0.0f, 0.0f), true);
        DrawAliasDetails();
        ImGui::EndChild();

        ImGui::End();
    }

    void AssetAliasManifestEditorPanel::DrawAliasDetails()
    {
        EditorWidgets::SectionHeader(
            EditorLocale::Text("Alias Details", "别名详情"),
            EditorLocale::Text("Choose a project asset or alias target. Missing targets are highlighted immediately.", "选择项目资产或别名目标，缺失目标会立即提示。"));

        YAML::Node root = m_Document.Root();
        std::vector<AliasRow> rows = BuildAliasRows(root);
        auto selected = std::find_if(rows.begin(), rows.end(), [&](const AliasRow& row)
        {
            return row.Alias == m_SelectedAlias;
        });
        if (selected == rows.end())
        {
            EditorWidgets::EmptyState(
                EditorLocale::Text("Select an alias.", "请选择一个别名。"),
                EditorLocale::Text("Alias details will appear here.", "别名详情会显示在这里。"));
            return;
        }

        std::string alias = selected->Alias;
        std::string target = selected->Target;
        const std::string originalAlias = alias;
        const std::string originalTarget = target;

        if (EditorWidgets::InputString("Alias", alias, 256)
            && alias != originalAlias
            && !alias.empty()
            && SetAliasTarget(root, alias, target))
        {
            RemoveAliasTarget(root, originalAlias);
            m_SelectedAlias = alias;
            m_Document.MarkDirty();
            m_Status = "Alias renamed.";
        }

        if (EditorContentPickers::DrawAssetField("Target",
            target,
            EditorWidgets::AssetReferenceKind::Any,
            512)
            && target != originalTarget
            && SetAliasTarget(root, m_SelectedAlias, target))
        {
            m_Document.MarkDirty();
            m_Status = "Alias target changed.";
        }

        if (target.empty())
        {
            EditorWidgets::InlineStatus("Target is empty.", EditorWidgets::StatusKind::Error);
        }
        else if (!TargetExists(target))
        {
            EditorWidgets::InlineStatus("Target is missing from the project.",
                EditorWidgets::StatusKind::Warning);
        }
        else
        {
            EditorWidgets::InlineStatus("Target is available.",
                EditorWidgets::StatusKind::Success);
        }

        DrawReferenceTools(m_SelectedAlias, target);

        ImGui::Separator();
        if (ImGui::Button("Delete Alias"))
        {
            if (RemoveAliasTarget(root, m_SelectedAlias))
            {
                m_SelectedAlias.clear();
                m_Document.MarkDirty();
                m_Status = "Alias deleted.";
            }
        }

        if (ImGui::BeginTabBar("##AliasManifestTabs"))
        {
            if (EditorGameplayShell::BeginRawPreviewTab("Advanced Raw Preview"))
            {
                EditorGameplayShell::DrawRawPreview(m_Document.GetRawPreview(),
                    "##AliasManifestRawPreview",
                    m_SourcePath.c_str());
                ImGui::EndTabItem();
            }
            ImGui::EndTabBar();
        }
    }

    void AssetAliasManifestEditorPanel::DrawReferenceTools(const std::string& alias, const std::string& target)
    {
        EditorWidgets::SectionHeader(
            EditorLocale::Text("Reference Replacement", "引用替换"),
            EditorLocale::Text("Replace exact hardcoded references in project text files with this stable alias.", "把项目文本文件里的硬编码引用精确替换成这个稳定别名。"));

        if (m_ReferenceSearchText.empty())
            m_ReferenceSearchText = target;

        EditorWidgets::InputString("Find Text", m_ReferenceSearchText, 512);
        ImGui::TextDisabled("Replace With");
        ImGui::SameLine(150.0f);
        ImGui::TextUnformatted(alias.c_str());

        const bool canReplace = !m_Document.IsDirty()
            && !alias.empty()
            && !m_ReferenceSearchText.empty()
            && m_ReferenceSearchText != alias;
        if (m_Document.IsDirty())
            EditorWidgets::InlineStatus("Save the manifest before replacing project references.", EditorWidgets::StatusKind::Warning);

        ImGui::BeginDisabled(!canReplace);
        if (ImGui::Button("Preview Replacements"))
            ApplyReferenceReplacement(m_ReferenceSearchText, alias, true);
        ImGui::SameLine();
        if (ImGui::Button("Replace With Alias"))
            ApplyReferenceReplacement(m_ReferenceSearchText, alias, false);
        ImGui::EndDisabled();

        if (!target.empty())
        {
            ImGui::SameLine();
            if (ImGui::SmallButton("Use Target"))
                m_ReferenceSearchText = target;
        }

        if (!m_ReferenceReplaceStatus.empty())
            EditorWidgets::InlineStatus(m_ReferenceReplaceStatus, EditorWidgets::StatusKind::Info);
    }

    void AssetAliasManifestEditorPanel::ApplyReferenceReplacement(
        const std::string& searchText,
        const std::string& replacementText,
        bool dryRun)
    {
        const ReferenceReplacementSummary summary = ReplaceProjectReferences(
            searchText,
            replacementText,
            m_SourcePath,
            dryRun);

        if (!summary.Error.empty())
        {
            m_ReferenceReplaceStatus = summary.Error;
            return;
        }

        std::ostringstream status;
        status << (dryRun ? "Preview: " : "Replaced ")
            << summary.Occurrences
            << " occurrence(s) in "
            << summary.FilesChanged
            << " file(s), scanned "
            << summary.FilesVisited
            << " file(s).";
        if (!summary.FirstChangedFile.empty())
            status << " First: " << summary.FirstChangedFile;
        m_ReferenceReplaceStatus = status.str();

        if (!dryRun)
            AssetAliasRegistry::Reload(m_SourcePath);
    }

} // namespace Wheatear
