#include "wtpch.h"
#include "PlayerConfig.h"

#include "Wheatear/Core/FileSystem.h"

#include <algorithm>
#include <cctype>
#include <fstream>
#include <sstream>
#include <string>

namespace Wheatear {

    namespace {

        static std::string Trim(const std::string& value)
        {
            const char* whitespace = " \t\r\n";
            const size_t begin = value.find_first_not_of(whitespace);
            if (begin == std::string::npos)
                return {};

            const size_t end = value.find_last_not_of(whitespace);
            return value.substr(begin, end - begin + 1);
        }

        static std::string Lower(std::string value)
        {
            std::transform(value.begin(), value.end(), value.begin(),
                [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
            return value;
        }

        static bool ParseBool(const std::string& value, bool fallback)
        {
            const std::string lowered = Lower(Trim(value));
            if (lowered == "1" || lowered == "true" || lowered == "yes" || lowered == "on")
                return true;
            if (lowered == "0" || lowered == "false" || lowered == "no" || lowered == "off")
                return false;
            return fallback;
        }

    } // namespace

    std::filesystem::path FindRuntimePlayerConfigPath(const std::filesystem::path& start)
    {
        std::filesystem::path cursor = start.empty()
            ? std::filesystem::current_path()
            : start;

        cursor = FileSystem::Normalize(cursor);
        while (!cursor.empty())
        {
            const std::filesystem::path candidate = cursor / "assets" / "game" / "player.config";
            if (std::filesystem::exists(candidate))
                return candidate;

            const std::filesystem::path parent = cursor.parent_path();
            if (parent == cursor)
                break;
            cursor = parent;
        }

        return {};
    }

    RuntimePlayerConfig LoadRuntimePlayerConfig(const std::filesystem::path& configPath)
    {
        RuntimePlayerConfig config;
        const std::filesystem::path resolvedConfigPath = configPath.empty()
            ? FindRuntimePlayerConfigPath()
            : configPath;
        if (resolvedConfigPath.empty())
            return config;

        std::ifstream input(resolvedConfigPath);
        if (!input.is_open())
            return config;

        std::string line;
        while (std::getline(input, line))
        {
            line = Trim(line);
            if (line.empty() || line[0] == '#')
                continue;

            const size_t separator = line.find('=');
            if (separator == std::string::npos)
                continue;

            const std::string key = Lower(Trim(line.substr(0, separator)));
            const std::string value = Trim(line.substr(separator + 1));

            if (key == "startupscene")
                config.StartupScene = value;
            else if (key == "enablescripts")
                config.EnableScripts = ParseBool(value, config.EnableScripts);
        }

        return config;
    }

    bool SaveRuntimePlayerConfig(const std::filesystem::path& configPath,
        const RuntimePlayerConfig& config,
        const char* generatorName)
    {
        std::ostringstream output;
        output << "# Generated by " << (generatorName ? generatorName : EngineInfo::Name) << ".\n";
        output << "StartupScene=" << config.StartupScene.generic_string() << "\n";
        output << "EnableScripts=" << (config.EnableScripts ? "true" : "false") << "\n";
        return FileSystem::WriteTextFile(configPath, output.str());
    }

} // namespace Wheatear
