#pragma once

// Shared file-internal helpers for the progression content editor, extracted
// from ProgressionContentEditorPanel.cpp so per-content-type translation units
// can be split off. Inline so each TU compiles independently.

#include "Editor/EditorContentPickers.h"
#include "Editor/GameplayEditorShell.h"
#include "Editor/EditorLocale.h"
#include "Editor/EditorWidgets.h"
#include "Editor/YamlTreeEditor.h"
#include "Wheatear/Assets/AssetAliasRegistry.h"
#include "Wheatear/Assets/AssetPath.h"
#include "Wheatear/Modules/Progression/ProgressionContent.h"

#include <yaml-cpp/yaml.h>

#include <imgui/imgui.h>

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace Wheatear::ProgressionContentEditorInternal {


        using namespace EditorWidgets;

        // Re-exported from the shared YAML tree widget so the rest of this
        // panel keeps using the same helpers (single source of truth).
        using YamlTreeEditor::NodeTypeLabel;
        using YamlTreeEditor::LastPathSegment;
        using YamlTreeEditor::ToLowerAscii;
        using YamlTreeEditor::ContainsInsensitive;
        using YamlTreeEditor::MapContainsKey;
        using YamlTreeEditor::MapKeysInOrder;
        using YamlTreeEditor::ScalarText;

        constexpr const char* DefaultHeader =
            "# Generated by Wheatear Progression Content Editor.\n"
            "# This file remains a runtime data source for progression content.\n\n";

        inline std::string HumanizeKey(std::string key)
        {
            for (char& c : key)
            {
                if (c == '_' || c == '-')
                    c = ' ';
            }
            return key;
        }

        constexpr const char* kMagicSwordCoreNodeId = "magic_sword_core";
        constexpr const char* kMagicSwordLv2NodeId = "magic_sword_lv2";
        constexpr float kPi = 3.14159265359f;

        struct SkillBranchLayout
        {
            const char* Prefix;
            float BaseDegrees;
            float CurveDegrees;
        };

        constexpr std::array<SkillBranchLayout, 5> kSkillBranchLayouts = {{
            { "ME", -90.0f, 50.0f },
            { "MA", -18.0f, 52.0f },
            { "FU", 54.0f, 52.0f },
            { "MO", 126.0f, 52.0f },
            { "LI", 198.0f, 50.0f },
        }};

        struct SkillFallbackLayout
        {
            std::string ParentId;
            ImVec2 Position = { 0.5f, 0.5f };
        };

        struct SkillGraphNode
        {
            size_t Index = 0;
            YAML::Node Node;
            std::string Id;
            std::string Name;
            std::string ParentId;
            std::string Branch;
            int UnlockChapter = 1;
            bool HasExplicitParent = false;
            bool HasExplicitPosition = false;
            ImVec2 Position = { 0.5f, 0.5f };
        };

        inline std::string SkillNodeId(const YAML::Node& node, size_t index)
        {
            const std::string id = ScalarText(node["id"]);
            return id.empty() ? "__missing_skill_id_" + std::to_string(index + 1) : id;
        }

        inline bool IsSyntheticSkillId(const std::string& id)
        {
            return id.rfind("__missing_skill_id_", 0) == 0;
        }

        inline int SkillNodeIndexFromId(const std::string& nodeId)
        {
            const size_t separator = nodeId.find('-');
            if (separator == std::string::npos || separator + 1 >= nodeId.size())
                return 0;

            try
            {
                return std::max(std::stoi(nodeId.substr(separator + 1)), 0);
            }
            catch (...)
            {
                return 0;
            }
        }

        inline bool ReadSkillNodePosition(const YAML::Node& node, ImVec2& position)
        {
            const YAML::Node value = node["position"];
            if (!value)
                return false;

            try
            {
                if (value.IsSequence() && value.size() >= 2)
                {
                    position.x = std::clamp(value[0].as<float>(position.x), 0.0f, 1.0f);
                    position.y = std::clamp(value[1].as<float>(position.y), 0.0f, 1.0f);
                    return true;
                }

                if (value.IsMap())
                {
                    position.x = std::clamp(value["x"].as<float>(position.x), 0.0f, 1.0f);
                    position.y = std::clamp(value["y"].as<float>(position.y), 0.0f, 1.0f);
                    return true;
                }
            }
            catch (...)
            {
                return false;
            }

            return false;
        }

        inline void WriteSkillNodePosition(YAML::Node node, float x, float y)
        {
            YAML::Node position(YAML::NodeType::Map);
            position["x"] = std::clamp(x, 0.0f, 1.0f);
            position["y"] = std::clamp(y, 0.0f, 1.0f);
            node["position"] = position;
        }

        inline std::string Shorten(std::string text, size_t maxLength)
        {
            if (text.size() <= maxLength)
                return text;
            if (maxLength <= 3)
                return text.substr(0, maxLength);
            return text.substr(0, maxLength - 3) + "...";
        }

        inline bool SkillNodeIdExists(const YAML::Node& skillNodes, const std::string& id)
        {
            if (!skillNodes || !skillNodes.IsSequence())
                return false;

            for (size_t i = 0; i < skillNodes.size(); ++i)
            {
                YAML::Node node = skillNodes[i];
                if (node.IsMap() && ScalarText(node["id"]) == id)
                    return true;
            }
            return false;
        }

        inline std::string MakeUniqueSkillNodeId(const YAML::Node& skillNodes, const std::string& base)
        {
            if (!SkillNodeIdExists(skillNodes, base))
                return base;

            for (int i = 2; i < 10000; ++i)
            {
                const std::string candidate = base + "_" + std::to_string(i);
                if (!SkillNodeIdExists(skillNodes, candidate))
                    return candidate;
            }

            return base + "_copy";
        }

        inline std::unordered_map<std::string, SkillFallbackLayout> BuildFallbackSkillTreeLayout(const std::vector<SkillGraphNode>& nodes)
        {
            std::unordered_map<std::string, SkillFallbackLayout> result;
            const auto core = std::find_if(nodes.begin(), nodes.end(), [](const SkillGraphNode& node)
            {
                return node.Id == kMagicSwordCoreNodeId;
            });
            if (core == nodes.end())
                return result;

            result[kMagicSwordCoreNodeId] = { "", { 0.50f, 0.50f } };
            if (std::find_if(nodes.begin(), nodes.end(), [](const SkillGraphNode& node)
            {
                return node.Id == kMagicSwordLv2NodeId;
            }) != nodes.end())
            {
                result[kMagicSwordLv2NodeId] = { kMagicSwordCoreNodeId, { 0.50f, 0.36f } };
            }

            for (const SkillBranchLayout& layout : kSkillBranchLayouts)
            {
                const std::string branchPrefix = std::string(layout.Prefix) + "-";
                std::vector<const SkillGraphNode*> branchNodes;
                for (const SkillGraphNode& node : nodes)
                {
                    if (node.Id.rfind(branchPrefix, 0) == 0)
                        branchNodes.push_back(&node);
                }

                std::sort(branchNodes.begin(), branchNodes.end(), [](const SkillGraphNode* a, const SkillGraphNode* b)
                {
                    const int aIndex = SkillNodeIndexFromId(a->Id);
                    const int bIndex = SkillNodeIndexFromId(b->Id);
                    if (aIndex != bIndex)
                        return aIndex < bIndex;
                    return a->Id < b->Id;
                });

                std::string parent = kMagicSwordCoreNodeId;
                const size_t count = branchNodes.size();
                for (size_t i = 0; i < count; ++i)
                {
                    const float t = count > 1 ? static_cast<float>(i) / static_cast<float>(count - 1) : 0.0f;
                    const float radius = 0.11f + 0.045f * static_cast<float>(i + 1);
                    const float angle = (layout.BaseDegrees + layout.CurveDegrees * t) * kPi / 180.0f;
                    const float ringOffset = (i % 3 == 0 ? 0.014f : (i % 3 == 1 ? -0.006f : 0.006f));
                    const ImVec2 position = {
                        0.50f + std::cos(angle) * (radius + ringOffset),
                        0.50f + std::sin(angle) * (radius + ringOffset)
                    };

                    result[branchNodes[i]->Id] = { parent, position };
                    parent = branchNodes[i]->Id;
                }
            }

            return result;
        }

        inline std::vector<SkillGraphNode> BuildSkillGraphNodes(YAML::Node skillNodes)
        {
            std::vector<SkillGraphNode> nodes;
            if (!skillNodes || !skillNodes.IsSequence())
                return nodes;

            nodes.reserve(skillNodes.size());
            for (size_t i = 0; i < skillNodes.size(); ++i)
            {
                YAML::Node node = skillNodes[i];
                if (!node.IsMap())
                    continue;

                SkillGraphNode graphNode;
                graphNode.Index = i;
                graphNode.Node = node;
                graphNode.Id = SkillNodeId(node, i);
                graphNode.Name = ScalarText(node["name"]);
                graphNode.ParentId = ScalarText(node["parentId"]);
                graphNode.Branch = ScalarText(node["branch"]);
                graphNode.UnlockChapter = node["unlockChapter"].as<int>(1);
                graphNode.HasExplicitParent = MapContainsKey(node, "parentId");
                graphNode.HasExplicitPosition = ReadSkillNodePosition(node, graphNode.Position);
                nodes.push_back(std::move(graphNode));
            }

            const auto fallback = BuildFallbackSkillTreeLayout(nodes);
            for (SkillGraphNode& node : nodes)
            {
                if (auto it = fallback.find(node.Id); it != fallback.end())
                {
                    if (!node.HasExplicitParent)
                        node.ParentId = it->second.ParentId;
                    if (!node.HasExplicitPosition)
                        node.Position = it->second.Position;
                }
            }

            return nodes;
        }

        inline int FindSkillGraphIndex(const std::vector<SkillGraphNode>& nodes, const std::string& id)
        {
            for (size_t i = 0; i < nodes.size(); ++i)
            {
                if (nodes[i].Id == id)
                    return static_cast<int>(i);
            }
            return -1;
        }

        inline ImVec2 SkillGraphToScreen(const ImVec2& canvasMin, const ImVec2& canvasSize, const ImVec2& position)
        {
            return {
                canvasMin.x + std::clamp(position.x, 0.0f, 1.0f) * canvasSize.x,
                canvasMin.y + std::clamp(position.y, 0.0f, 1.0f) * canvasSize.y
            };
        }

        inline ImVec2 SkillGraphFromScreen(const ImVec2& canvasMin, const ImVec2& canvasSize, const ImVec2& position)
        {
            return {
                canvasSize.x > 0.0f ? std::clamp((position.x - canvasMin.x) / canvasSize.x, 0.0f, 1.0f) : 0.5f,
                canvasSize.y > 0.0f ? std::clamp((position.y - canvasMin.y) / canvasSize.y, 0.0f, 1.0f) : 0.5f
            };
        }

        inline bool DrawSkillTextField(YAML::Node node, const char* label, const char* key, size_t capacity = 512)
        {
            std::string value = ScalarText(node[key]);
            if (!EditorWidgets::InputString(label, value, capacity))
                return false;

            node[key] = value;
            return true;
        }

        inline bool DrawSkillMultilineField(YAML::Node node, const char* label, const char* key)
        {
            std::string value = ScalarText(node[key]);
            if (!EditorWidgets::InputMultilineString(label, value, ImVec2(-1.0f, 82.0f), std::max<size_t>(2048, value.size() + 256)))
                return false;

            node[key] = value;
            return true;
        }

        inline bool DrawTextField(YAML::Node node, const char* label, const char* key, size_t capacity = 512)
        {
            std::string value = ScalarText(node[key]);
            if (!EditorWidgets::InputString(label, value, capacity))
                return false;

            node[key] = value;
            return true;
        }

        inline YAML::Node EnsureSequence(YAML::Node node, const char* key);
        inline bool DrawStringListField(YAML::Node node,
            const char* label,
            const char* key,
            const std::vector<std::string>& choices);

        inline std::vector<std::string> ChapterChoices()
        {
            std::vector<std::string> choices;
            for (int chapter = 0; chapter <= 13; ++chapter)
                choices.push_back("Chapter " + std::to_string(chapter));
            return choices;
        }

        inline bool DrawAssetField(YAML::Node node,
            const char* label,
            const char* key,
            EditorWidgets::AssetReferenceKind kind,
            size_t capacity = 512)
        {
            std::string value = ScalarText(node[key]);
            if (!EditorWidgets::DrawAssetReferenceField(label, value, kind, capacity))
                return false;

            node[key] = value;
            return true;
        }

        inline std::vector<std::string> BuildContentIds(const char* kind)
        {
            std::vector<std::string> ids;
            const auto& content = ProgressionContent::Get();
            if (std::string(kind ? kind : "") == "skill")
            {
                ids.reserve(content.SkillNodes.size());
                for (const auto& item : content.SkillNodes)
                    ids.push_back(item.Id);
            }
            else if (std::string(kind ? kind : "") == "equipment")
            {
                ids.reserve(content.Equipment.size());
                for (const auto& item : content.Equipment)
                    ids.push_back(item.Id);
            }
            else if (std::string(kind ? kind : "") == "equipmentSlot")
            {
                ids.reserve(content.EquipmentSlots.size());
                for (const auto& item : content.EquipmentSlots)
                    ids.push_back(item.Id);
            }
            else if (std::string(kind ? kind : "") == "dungeon")
            {
                ids.reserve(content.Dungeons.size());
                for (const auto& item : content.Dungeons)
                    ids.push_back(item.Id);
            }
            else if (std::string(kind ? kind : "") == "material")
            {
                ids.reserve(content.Materials.size());
                for (const auto& item : content.Materials)
                    ids.push_back(item.ItemId);
            }
            else if (std::string(kind ? kind : "") == "relationship")
            {
                ids.reserve(content.Relationships.size());
                for (const auto& item : content.Relationships)
                    ids.push_back(item.CharacterId);
            }

            ids.erase(std::remove_if(ids.begin(), ids.end(), [](const std::string& id)
            {
                return id.empty();
            }), ids.end());
            std::sort(ids.begin(), ids.end());
            ids.erase(std::unique(ids.begin(), ids.end()), ids.end());
            return ids;
        }

        inline bool DrawIdCombo(const char* label, std::string& value, const std::vector<std::string>& ids)
        {
            bool changed = false;
            ImGui::TextDisabled("%s", label ? label : "Id");
            ImGui::SameLine(150.0f);
            ImGui::PushID(label ? label : "id_combo");
            ImGui::SetNextItemWidth(260.0f);
            if (ImGui::BeginCombo("##value", value.empty() ? EditorLocale::Text("(none)", "(无)") : value.c_str()))
            {
                if (ImGui::Selectable(EditorLocale::Text("(none)", "(无)"), value.empty()))
                {
                    value.clear();
                    changed = true;
                }
                for (const std::string& id : ids)
                {
                    const bool selected = value == id;
                    const std::string itemLabel = EditorWidgets::LabelWithId(id, "progression_id:" + id);
                    if (ImGui::Selectable(itemLabel.c_str(), selected))
                    {
                        value = id;
                        changed = true;
                    }
                    if (selected)
                        ImGui::SetItemDefaultFocus();
                }
                ImGui::EndCombo();
            }
            ImGui::SameLine();
            if (ImGui::SmallButton(EditorLocale::Text("Clear", "清空")))
            {
                value.clear();
                changed = true;
            }
            ImGui::PopID();
            return changed;
        }

        inline bool DrawIdField(YAML::Node node, const char* label, const char* key, const char* kind)
        {
            std::string value = ScalarText(node[key]);
            if (!DrawIdCombo(label, value, BuildContentIds(kind)))
                return false;

            node[key] = value;
            return true;
        }

        inline void AppendDelimitedToken(std::string& value, const std::string& token)
        {
            if (token.empty())
                return;

            if (!value.empty())
            {
                const char last = value.back();
                if (last != ' ' && last != '/' && last != '\n')
                    value += " / ";
                else if (last == ' ')
                    value += "/ ";
            }
            value += token;
        }

        inline bool DrawAppendTokenButton(const char* label,
            std::string& value,
            const std::vector<std::string>& choices,
            const char* prefix = "",
            const char* suffix = "")
        {
            const bool hasChoices = !choices.empty();
            bool changed = false;
            const std::string popupId = std::string("##append_token_") + (label ? label : "value");
            ImGui::BeginDisabled(!hasChoices);
            if (ImGui::SmallButton(label))
                ImGui::OpenPopup(popupId.c_str());
            ImGui::EndDisabled();

            if (!hasChoices)
                return false;

            if (ImGui::BeginPopup(popupId.c_str()))
            {
                for (const std::string& choice : choices)
                {
                    if (ImGui::Selectable(choice.c_str()))
                    {
                        AppendDelimitedToken(value, std::string(prefix ? prefix : "") + choice + (suffix ? suffix : ""));
                        changed = true;
                        ImGui::CloseCurrentPopup();
                    }
                }
                ImGui::EndPopup();
            }
            return changed;
        }

        inline bool DrawRewardTokenButtons(std::string& value)
        {
            bool changed = false;
            changed |= DrawAppendTokenButton("+ Material", value, BuildContentIds("material"), "", " x1");
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Equipment", value, BuildContentIds("equipment"));
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Skill", value, BuildContentIds("skill"));
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Dungeon", value, BuildContentIds("dungeon"));
            return changed;
        }

        inline bool DrawRequirementTokenButtons(std::string& value)
        {
            bool changed = false;
            changed |= DrawAppendTokenButton("+ Chapter", value, ChapterChoices());
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Skill", value, BuildContentIds("skill"));
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Material", value, BuildContentIds("material"), "", " x1");
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Dungeon", value, BuildContentIds("dungeon"));
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Relationship", value, BuildContentIds("relationship"));
            ImGui::SameLine();
            changed |= DrawAppendTokenButton("+ Flag", value, EditorContentPickers::StoryFlags());
            return changed;
        }

        inline bool DrawChoiceField(YAML::Node node,
            const char* label,
            const char* key,
            const std::vector<std::string>& choices,
            size_t capacity = 256)
        {
            std::string value = ScalarText(node[key]);
            if (!EditorContentPickers::DrawStringPicker(label, value, choices, capacity, "Custom"))
                return false;

            node[key] = value;
            return true;
        }

        inline std::vector<std::string> DungeonCategoryChoices()
        {
            std::vector<std::string> choices = {
                "Main",
                EditorLocale::Text("Material", "材料"),
                "Side",
                "Boss",
                "Tutorial"
            };

            const auto& content = ProgressionContent::Get();
            for (const auto& dungeon : content.Dungeons)
                choices.push_back(dungeon.Category);
            EditorContentPickers::SortUnique(choices);
            return choices;
        }

        inline std::vector<std::string> SkillBranchChoices()
        {
            std::vector<std::string> choices = {
                "Core",
                "Melee",
                "Magic",
                "Fusion",
                "Mobility",
                "Limit",
                "Custom"
            };

            const auto& content = ProgressionContent::Get();
            for (const auto& skill : content.SkillNodes)
                choices.push_back(skill.Branch);
            EditorContentPickers::SortUnique(choices);
            return choices;
        }

        inline bool DrawRewardTextField(YAML::Node node, const char* label, const char* key)
        {
            bool changed = false;
            std::string value = ScalarText(node[key]);
            ImGui::PushID(key);
            changed |= EditorWidgets::InputMultilineString(label,
                value,
                ImVec2(-1.0f, 72.0f),
                std::max<size_t>(2048, value.size() + 256));
            changed |= DrawRewardTokenButtons(value);
            ImGui::PopID();

            if (changed)
                node[key] = value;
            return changed;
        }

        inline bool DrawRequirementField(YAML::Node node, const char* label, const char* key)
        {
            bool changed = false;
            std::string value = ScalarText(node[key]);
            ImGui::PushID(key);
            changed |= EditorWidgets::InputString(label, value, 512);
            changed |= DrawRequirementTokenButtons(value);
            ImGui::PopID();

            if (changed)
                node[key] = value;
            return changed;
        }

        inline bool DrawStoryFlagListField(YAML::Node node, const char* label, const char* key)
        {
            return DrawStringListField(node, label, key, EditorContentPickers::StoryFlags());
        }

        inline bool DrawRewardSummaryListEditor(YAML::Node root)
        {
            bool changed = false;
            YAML::Node summaries = EnsureSequence(root, "dungeonRewardSummary");
            EditorWidgets::SectionHeader(EditorLocale::Text("Dungeon Reward Summary", "地牢奖励摘要"),
                "Narrative reward lines shown by progression result pages.");

            int removeIndex = -1;
            for (size_t i = 0; i < summaries.size(); ++i)
            {
                ImGui::PushID(static_cast<int>(i));
                bool lineChanged = false;
                std::string value = ScalarText(summaries[i]);
                ImGui::TextDisabled("#%d", static_cast<int>(i + 1));
                lineChanged |= EditorWidgets::InputMultilineString("##summary",
                    value,
                    ImVec2(-1.0f, 70.0f),
                    std::max<size_t>(1024, value.size() + 256));
                lineChanged |= DrawRewardTokenButtons(value);
                ImGui::SameLine();
                if (ImGui::SmallButton(EditorLocale::Text("Remove", "移除")))
                    removeIndex = static_cast<int>(i);
                if (lineChanged)
                {
                    summaries[i] = value;
                    changed = true;
                }
                ImGui::Separator();
                ImGui::PopID();
            }

            if (removeIndex >= 0)
            {
                summaries.remove(removeIndex);
                changed = true;
            }

            if (ImGui::Button(EditorLocale::Text("Add Reward Summary", "添加奖励摘要")))
            {
                summaries.push_back("");
                changed = true;
            }
            return changed;
        }

        inline bool DrawMultilineField(YAML::Node node, const char* label, const char* key, float height = 74.0f)
        {
            std::string value = ScalarText(node[key]);
            if (!EditorWidgets::InputMultilineString(label, value, ImVec2(-1.0f, height), std::max<size_t>(2048, value.size() + 256)))
                return false;

            node[key] = value;
            return true;
        }

        inline bool DrawIntField(YAML::Node node, const char* label, const char* key, int fallback = 0, int minValue = 0, int maxValue = 999)
        {
            int value = node[key].as<int>(fallback);
            if (!ImGui::DragInt(label, &value, 1.0f, minValue, maxValue))
                return false;

            node[key] = value;
            return true;
        }

        inline bool DrawBoolField(YAML::Node node, const char* label, const char* key, bool fallback = false)
        {
            bool value = node[key].as<bool>(fallback);
            if (!ImGui::Checkbox(label, &value))
                return false;

            node[key] = value;
            return true;
        }

        inline YAML::Node EnsureSequence(YAML::Node node, const char* key)
        {
            YAML::Node sequence = node[key];
            if (!sequence || !sequence.IsSequence())
            {
                node[key] = YAML::Node(YAML::NodeType::Sequence);
                sequence = node[key];
            }
            return sequence;
        }

        inline YAML::Node EnsureMap(YAML::Node node, const char* key)
        {
            YAML::Node map = node[key];
            if (!map || !map.IsMap())
            {
                node[key] = YAML::Node(YAML::NodeType::Map);
                map = node[key];
            }
            return map;
        }

        inline bool DrawStringListField(YAML::Node node,
            const char* label,
            const char* key,
            const std::vector<std::string>& choices = {})
        {
            bool changed = false;
            YAML::Node sequence = EnsureSequence(node, key);
            if (ImGui::TreeNodeEx(label, ImGuiTreeNodeFlags_DefaultOpen, "%s (%d)", label, static_cast<int>(sequence.size())))
            {
                int removeIndex = -1;
                for (size_t i = 0; i < sequence.size(); ++i)
                {
                    ImGui::PushID(static_cast<int>(i));
                    std::string value = ScalarText(sequence[i]);
                    ImGui::SetNextItemWidth(-64.0f);
                    if (EditorWidgets::InputString("##value", value, 256))
                    {
                        sequence[i] = value;
                        changed = true;
                    }
                    if (!choices.empty())
                    {
                        ImGui::SameLine();
                        if (ImGui::SmallButton(EditorLocale::Text("Select", "选择")))
                            ImGui::OpenPopup("##select_item");
                        if (ImGui::BeginPopup("##select_item"))
                        {
                            for (const std::string& choice : choices)
                            {
                                const bool selected = value == choice;
                                const std::string itemLabel = EditorWidgets::LabelWithId(choice, "progression_list_choice:" + choice);
                                if (ImGui::Selectable(itemLabel.c_str(), selected))
                                {
                                    sequence[i] = choice;
                                    changed = true;
                                    ImGui::CloseCurrentPopup();
                                }
                            }
                            ImGui::EndPopup();
                        }
                    }
                    ImGui::SameLine();
                    if (ImGui::SmallButton(EditorLocale::Text("Remove", "移除")))
                        removeIndex = static_cast<int>(i);
                    ImGui::PopID();
                }

                if (removeIndex >= 0)
                {
                    sequence.remove(removeIndex);
                    changed = true;
                }

                if (ImGui::SmallButton(EditorLocale::Text("Add Item", "添加条目")))
                {
                    sequence.push_back(choices.empty() ? "" : choices.front());
                    changed = true;
                }
                ImGui::TreePop();
            }
            return changed;
        }

        inline bool DrawStringMapField(YAML::Node node,
            const char* label,
            const char* key,
            const std::vector<std::string>& keyChoices = {},
            const std::vector<std::string>& valueChoices = {})
        {
            bool changed = false;
            YAML::Node map = EnsureMap(node, key);
            if (ImGui::TreeNodeEx(label, ImGuiTreeNodeFlags_DefaultOpen, "%s (%d)", label, static_cast<int>(map.size())))
            {
                std::string removeKey;
                const std::vector<std::string> keys = MapKeysInOrder(map);
                for (const std::string& entryKey : keys)
                {
                    ImGui::PushID(entryKey.c_str());
                    std::string editableKey = entryKey;
                    std::string value = ScalarText(map[entryKey]);
                    ImGui::SetNextItemWidth(150.0f);
                    if (EditorWidgets::InputString(EditorLocale::Text("Key", "键"), editableKey, 128) && !editableKey.empty() && editableKey != entryKey)
                    {
                        map[editableKey] = value;
                        map.remove(entryKey);
                        changed = true;
                    }
                    if (!keyChoices.empty())
                    {
                        ImGui::SameLine();
                        if (ImGui::SmallButton(EditorLocale::Text("Slot", "槽位")))
                            ImGui::OpenPopup("##select_key");
                        if (ImGui::BeginPopup("##select_key"))
                        {
                            for (const std::string& choice : keyChoices)
                            {
                                const bool selected = editableKey == choice;
                                const std::string itemLabel = EditorWidgets::LabelWithId(choice, "progression_map_key:" + choice);
                                if (ImGui::Selectable(itemLabel.c_str(), selected))
                                {
                                    map[choice] = value;
                                    map.remove(entryKey);
                                    editableKey = choice;
                                    changed = true;
                                    ImGui::CloseCurrentPopup();
                                }
                            }
                            ImGui::EndPopup();
                        }
                    }
                    ImGui::SameLine();
                    ImGui::SetNextItemWidth(-64.0f);
                    if (EditorWidgets::InputString(EditorLocale::Text("Value", "值"), value, 256))
                    {
                        map[editableKey] = value;
                        changed = true;
                    }
                    if (!valueChoices.empty())
                    {
                        ImGui::SameLine();
                        if (ImGui::SmallButton("Item"))
                            ImGui::OpenPopup("##select_value");
                        if (ImGui::BeginPopup("##select_value"))
                        {
                            for (const std::string& choice : valueChoices)
                            {
                                const bool selected = value == choice;
                                const std::string itemLabel = EditorWidgets::LabelWithId(choice, "progression_map_value:" + choice);
                                if (ImGui::Selectable(itemLabel.c_str(), selected))
                                {
                                    map[editableKey] = choice;
                                    changed = true;
                                    ImGui::CloseCurrentPopup();
                                }
                            }
                            ImGui::EndPopup();
                        }
                    }
                    ImGui::SameLine();
                    if (ImGui::SmallButton(EditorLocale::Text("Remove", "移除")))
                        removeKey = editableKey;
                    ImGui::PopID();
                }

                if (!removeKey.empty())
                {
                    map.remove(removeKey);
                    changed = true;
                }

                if (ImGui::SmallButton(EditorLocale::Text("Add Pair", "添加键值对")))
                {
                    std::string keyName = "item";
                    for (int i = 2; MapContainsKey(map, keyName); ++i)
                        keyName = "item" + std::to_string(i);
                    map[keyName] = "";
                    changed = true;
                }
                ImGui::TreePop();
            }
            return changed;
        }

        inline bool DrawCostsField(YAML::Node node)
        {
            bool changed = false;
            YAML::Node costs = EnsureSequence(node, "costs");
            if (ImGui::TreeNodeEx(EditorLocale::Text("Costs", "消耗"), ImGuiTreeNodeFlags_DefaultOpen, "Costs (%d)", static_cast<int>(costs.size())))
            {
                int removeIndex = -1;
                for (size_t i = 0; i < costs.size(); ++i)
                {
                    YAML::Node cost = costs[i];
                    ImGui::PushID(static_cast<int>(i));
                    ImGui::Text("#%d", static_cast<int>(i + 1));
                    changed |= DrawIdField(cost, "Item", "item", "material");
                    changed |= DrawTextField(cost, "Name", "name", 128);
                    ImGui::SetNextItemWidth(110.0f);
                    changed |= DrawIntField(cost, "Amount", "amount", 1, 0, 999);
                    ImGui::SameLine();
                    if (ImGui::SmallButton(EditorLocale::Text("Remove", "移除")))
                        removeIndex = static_cast<int>(i);
                    ImGui::PopID();
                }

                if (removeIndex >= 0)
                {
                    costs.remove(removeIndex);
                    changed = true;
                }

                if (ImGui::SmallButton(EditorLocale::Text("Add Cost", "添加消耗")))
                {
                    YAML::Node cost(YAML::NodeType::Map);
                    cost["item"] = "";
                    cost["name"] = "";
                    cost["amount"] = 1;
                    costs.push_back(cost);
                    changed = true;
                }
                ImGui::TreePop();
            }
            return changed;
        }

        inline bool DrawAttributeBonusField(YAML::Node node)
        {
            bool changed = false;
            YAML::Node bonus = EnsureMap(node, "attributeBonus");
            if (ImGui::TreeNodeEx("Attribute Bonus", ImGuiTreeNodeFlags_DefaultOpen))
            {
                changed |= DrawIntField(bonus, "HP", "HP", 0, -9999, 9999);
                changed |= DrawIntField(bonus, "ATK", "ATK", 0, -9999, 9999);
                changed |= DrawIntField(bonus, "DEF", "DEF", 0, -9999, 9999);
                changed |= DrawIntField(bonus, "MATK", "MATK", 0, -9999, 9999);
                changed |= DrawIntField(bonus, "MDEF", "MDEF", 0, -9999, 9999);
                ImGui::TreePop();
            }
            return changed;
        }

        inline YAML::Node MakeDefaultContentRecord(const std::string& selectedKey)
        {
            YAML::Node node(YAML::NodeType::Map);
            if (selectedKey == "materials")
            {
                node["id"] = "NEW-MATERIAL";
                node["name"] = "New Material";
            }
            else if (selectedKey == "equipment")
            {
                node["id"] = "new_equipment";
                node["name"] = "New Equipment";
                node["slot"] = "";
                node["page"] = 1;
                node["status"] = "";
                node["stats"] = "";
                node["source"] = "";
                node["description"] = "";
                node["slotId"] = "";
                node["icon"] = "";
            }
            else if (selectedKey == "equipmentSlots")
            {
                node["id"] = "new_slot";
                node["name"] = "New Slot";
            }
            else if (selectedKey == "dungeons")
            {
                node["id"] = "NEW_DUNGEON";
                node["name"] = "New Dungeon";
                node["category"] = "";
                node["recommendedLevel"] = 1;
                node["statusWhenLocked"] = "";
                node["statusWhenUnlocked"] = "";
                node["firstClearRewardText"] = "";
                node["repeatRewardText"] = "";
                node["objectiveOnClear"] = "";
                node["firstClearNotification"] = "";
                node["unlocksOnFirstClear"] = YAML::Node(YAML::NodeType::Sequence);
                node["flagsOnClear"] = YAML::Node(YAML::NodeType::Sequence);
            }
            else if (selectedKey == "relationships")
            {
                node["id"] = "new_relationship";
                node["name"] = "New Relationship";
                node["affinity"] = 0;
                node["supportLevel"] = 0;
                node["unlocked"] = false;
                node["role"] = "";
                node["nextMilestone"] = "";
            }
            return node;
        }

        inline const char* RootKeyForSelectedAsset(const std::string& selectedKey)
        {
            if (selectedKey == "materials") return "materials";
            if (selectedKey == "equipment") return "equipment";
            if (selectedKey == "equipmentSlots") return "equipmentSlots";
            if (selectedKey == "dungeons") return "dungeons";
            if (selectedKey == "relationships") return "relationships";
            return nullptr;
        }

        inline std::string RecordId(const YAML::Node& node, size_t index)
        {
            const std::string id = ScalarText(node["id"]);
            return id.empty() ? "__record_" + std::to_string(index + 1) : id;
        }

        inline std::string RecordTitle(const YAML::Node& node, size_t index)
        {
            const std::string id = RecordId(node, index);
            const std::string name = ScalarText(node["name"]);
            return name.empty() ? id : id + "  " + name;
        }

        inline bool RecordIdExists(const YAML::Node& sequence, const std::string& id)
        {
            if (!sequence || !sequence.IsSequence())
                return false;

            for (size_t i = 0; i < sequence.size(); ++i)
            {
                if (ScalarText(sequence[i]["id"]) == id)
                    return true;
            }
            return false;
        }

        inline std::string MakeUniqueRecordId(const YAML::Node& sequence, const std::string& base)
        {
            if (!RecordIdExists(sequence, base))
                return base;

            for (int i = 2; i < 10000; ++i)
            {
                const std::string candidate = base + "_" + std::to_string(i);
                if (!RecordIdExists(sequence, candidate))
                    return candidate;
            }
            return base + "_copy";
        }


} // namespace Wheatear::ProgressionContentEditorInternal
